// SCALAR — Adaptive Question Bank
// 7 levels, topic-tagged, enriched with explanations and steps

const LEVELS = {
  ARITHMETIC: 0, EARLY_ALGEBRA: 1, ADVANCED_ALGEBRA: 2,
  GEOMETRY: 3, PRECALC: 4, CALC_INTRO: 5, CALC_ADVANCED: 6
};

const LEVEL_NAMES = [
  'Arithmetic', 'Early Algebra', 'Advanced Algebra',
  'Geometry', 'Pre-Calculus', 'Calculus I', 'Calculus II'
];

// Maps topic → which lesson page slug to link to when user gets it wrong
const TOPIC_LESSON_MAP = {
  'Fractions':         { level: 0, slug: 'fractions' },
  'Percentages':       { level: 0, slug: 'percentages' },
  'Exponents':         { level: 0, slug: 'exponents' },
  'Order of Operations':{ level: 0, slug: 'order-of-operations' },
  'Integers':          { level: 0, slug: 'integers' },
  'Decimals':          { level: 0, slug: 'decimals' },
  'Ratios':            { level: 0, slug: 'ratios' },
  'Primes & Factors':  { level: 0, slug: 'primes' },
  'Square Roots':      { level: 0, slug: 'roots' },
  'Probability':       { level: 0, slug: 'probability' },
  'Linear Equations':  { level: 1, slug: 'linear-equations' },
  'Slope & Lines':     { level: 1, slug: 'slope' },
  'Systems of Equations':{ level: 1, slug: 'systems' },
  'Inequalities':      { level: 1, slug: 'inequalities' },
  'Factoring':         { level: 1, slug: 'factoring' },
  'Functions':         { level: 1, slug: 'functions' },
  'Absolute Value':    { level: 1, slug: 'absolute-value' },
  'Exponent Rules':    { level: 1, slug: 'exponent-rules' },
  'Logarithms':        { level: 1, slug: 'logarithms' },
  'Complex Numbers':   { level: 2, slug: 'complex-numbers' },
  'Sequences & Series':{ level: 2, slug: 'sequences' },
  'Rational Expressions':{ level: 2, slug: 'rational-expressions' },
  'Polynomial Division':{ level: 2, slug: 'polynomial-division' },
  'Combinatorics':     { level: 2, slug: 'combinatorics' },
  'Trig Basics':       { level: 2, slug: 'trig-basics' },
  'Triangles':         { level: 3, slug: 'triangles' },
  'Circles':           { level: 3, slug: 'circles' },
  'Area & Volume':     { level: 3, slug: 'area-volume' },
  'Coordinate Geometry':{ level: 3, slug: 'coordinate-geometry' },
  'Congruence & Similarity':{ level: 3, slug: 'similarity' },
  'Proofs':            { level: 3, slug: 'proofs' },
  'Trig Functions':    { level: 4, slug: 'trig-functions' },
  'Trig Identities':   { level: 4, slug: 'trig-identities' },
  'Polar Coordinates': { level: 4, slug: 'polar' },
  'Limits':            { level: 4, slug: 'limits' },
  'Conic Sections':    { level: 4, slug: 'conics' },
  'Derivatives':       { level: 5, slug: 'derivatives' },
  'Chain Rule':        { level: 5, slug: 'chain-rule' },
  'Integrals':         { level: 5, slug: 'integrals' },
  'Fundamental Theorem':{ level: 5, slug: 'ftc' },
  'Optimization':      { level: 5, slug: 'optimization' },
  'Related Rates':     { level: 5, slug: 'related-rates' },
  'Integration Techniques':{ level: 6, slug: 'integration-techniques' },
  'Series & Convergence':{ level: 6, slug: 'series' },
  'Taylor Series':     { level: 6, slug: 'taylor' },
  'Applications of Integration':{ level: 6, slug: 'applications' },
};

const questions = {
  0: [
    { q: "What is 17 × 8?", opts: ["126", "136", "144", "156"], ans: 1, topic: "Integers", hint: "Break it: (10+7)×8 = 80+56", explanation: "17 × 8 = 136. Split 17 into 10+7, then 80+56=136.", steps: ["10 × 8 = 80", "7 × 8 = 56", "80 + 56 = 136"] },
    { q: "What is 144 ÷ 12?", opts: ["10", "11", "12", "13"], ans: 2, topic: "Integers", hint: "12 × 12 = ?", explanation: "12 × 12 = 144, so 144 ÷ 12 = 12." },
    { q: "What is 3/4 + 1/3?", opts: ["4/7", "13/12", "5/7", "1/2"], ans: 1, topic: "Fractions", hint: "Find LCM of 4 and 3, then convert both fractions", explanation: "LCD = 12. 3/4 = 9/12, 1/3 = 4/12. Sum = 13/12.", steps: ["LCD(4,3) = 12", "3/4 → 9/12", "1/3 → 4/12", "9/12 + 4/12 = 13/12"] },
    { q: "What is 2/5 × 5/6?", opts: ["1/3", "7/11", "1/4", "10/30"], ans: 0, topic: "Fractions", hint: "Multiply tops, multiply bottoms, simplify", explanation: "(2×5)/(5×6) = 10/30 = 1/3." },
    { q: "What is 15% of 200?", opts: ["20", "25", "30", "35"], ans: 2, topic: "Percentages", hint: "15% = 0.15. Multiply.", explanation: "0.15 × 200 = 30.", steps: ["15% = 0.15", "0.15 × 200 = 30"] },
    { q: "What is 3² + 4²?", opts: ["14", "25", "49", "7"], ans: 1, topic: "Exponents", hint: "Square each, then add", explanation: "9 + 16 = 25. (3-4-5 Pythagorean triple!)" },
    { q: "Simplify: 48/64", opts: ["2/3", "3/4", "4/5", "6/8"], ans: 1, topic: "Fractions", hint: "GCF(48,64) = 16", explanation: "48/16 = 3, 64/16 = 4. Result: 3/4." },
    { q: "What is 0.25 × 0.4?", opts: ["0.1", "0.01", "1.0", "0.065"], ans: 0, topic: "Decimals", hint: "Think: 1/4 × 2/5", explanation: "0.25 × 0.4 = 0.1" },
    { q: "What is the LCM of 4 and 6?", opts: ["8", "10", "12", "24"], ans: 2, topic: "Primes & Factors", hint: "LCM = (4×6)/GCF(4,6). GCF = 2.", explanation: "LCM(4,6) = 24/2 = 12" },
    { q: "What is the GCF of 24 and 36?", opts: ["6", "8", "12", "18"], ans: 2, topic: "Primes & Factors", hint: "List factors of each number", explanation: "GCF = 12. (Factors of 24: 1,2,3,4,6,8,12,24; 36: 1,2,3,4,6,9,12,18,36)" },
    { q: "Convert 3/8 to a decimal.", opts: ["0.325", "0.375", "0.425", "0.275"], ans: 1, topic: "Decimals", hint: "Divide 3 by 8", explanation: "3 ÷ 8 = 0.375" },
    { q: "What is 2³ × 2²?", opts: ["2⁵", "2⁶", "4⁵", "2⁴"], ans: 0, topic: "Exponents", hint: "Same base: add the exponents", explanation: "2³ × 2² = 2^(3+2) = 2⁵" },
    { q: "What is (-3) × (-4)?", opts: ["-12", "-7", "7", "12"], ans: 3, topic: "Integers", hint: "Negative × Negative = Positive", explanation: "(-3) × (-4) = 12" },
    { q: "What is 5! (5 factorial)?", opts: ["25", "60", "100", "120"], ans: 3, topic: "Combinatorics", hint: "5! = 5 × 4 × 3 × 2 × 1", explanation: "5! = 120" },
    { q: "What is 7/8 - 1/4?", opts: ["5/8", "6/8", "3/4", "1/2"], ans: 0, topic: "Fractions", hint: "Convert 1/4 to eighths: 1/4 = 2/8", explanation: "7/8 - 2/8 = 5/8" },
    { q: "What is √144?", opts: ["11", "12", "13", "14"], ans: 1, topic: "Square Roots", hint: "12 × 12 = ?", explanation: "√144 = 12" },
    { q: "What is 30% of 150?", opts: ["35", "40", "45", "50"], ans: 2, topic: "Percentages", hint: "30% = 0.30", explanation: "0.30 × 150 = 45" },
    { q: "What is (-5) + 8 - 3?", opts: ["0", "1", "6", "-6"], ans: 0, topic: "Integers", hint: "-5 + 8 = 3, then 3 - 3 = ?", explanation: "-5 + 8 = 3. 3 - 3 = 0." },
    { q: "Which is largest: 3/5, 5/8, 7/10, 2/3?", opts: ["3/5", "5/8", "7/10", "2/3"], ans: 2, topic: "Fractions", hint: "Convert to decimals: 3/5=0.6, 5/8=0.625, 7/10=0.7, 2/3≈0.667", explanation: "7/10 = 0.7 is the largest." },
    { q: "What is 2.5²?", opts: ["5", "5.25", "6", "6.25"], ans: 3, topic: "Decimals", hint: "2.5 × 2.5", explanation: "2.5 × 2.5 = 6.25" },
    { q: "What is 4/9 ÷ 2/3?", opts: ["8/27", "2/3", "6/9", "2/9"], ans: 1, topic: "Fractions", hint: "Dividing by a fraction = multiplying by its reciprocal", explanation: "4/9 × 3/2 = 12/18 = 2/3", steps: ["Flip: 2/3 → 3/2", "4/9 × 3/2 = 12/18", "Simplify: 2/3"] },
    { q: "If a shirt costs $40 and is 25% off, what is the sale price?", opts: ["$25", "$28", "$30", "$32"], ans: 2, topic: "Percentages", hint: "Discount = 25% of $40 = $10", explanation: "$40 - $10 = $30" },
    { q: "What is the absolute value of -17?", opts: ["-17", "0", "17", "289"], ans: 2, topic: "Integers", hint: "|x| = distance from zero, always ≥ 0", explanation: "|-17| = 17" },
    { q: "Round 3.748 to the nearest tenth.", opts: ["3.7", "3.74", "3.75", "3.8"], ans: 0, topic: "Decimals", hint: "Tenths digit is 7. Hundredths is 4 (< 5), so round down.", explanation: "3.748 → tenths is 7, hundredths=4 < 5 → stays 3.7" },
    { q: "What is 12³?", opts: ["36", "144", "1,728", "1,440"], ans: 2, topic: "Exponents", hint: "12² = 144. Then 144 × 12 = ?", explanation: "12³ = 144 × 12 = 1,728" },
    { q: "What is 5/6 of 48?", opts: ["36", "38", "40", "42"], ans: 2, topic: "Fractions", hint: "Divide 48 by 6, multiply by 5", explanation: "48 ÷ 6 = 8. 8 × 5 = 40." },
    { q: "A ratio is 3:5. If the first part is 12, what is the second?", opts: ["15", "18", "20", "25"], ans: 2, topic: "Ratios", hint: "Scale factor = 12/3 = 4", explanation: "Second = 5 × 4 = 20" },
    { q: "What is 0.6 as a fraction in lowest terms?", opts: ["6/10", "3/5", "2/3", "60/100"], ans: 1, topic: "Decimals", hint: "0.6 = 6/10. GCF(6,10)=2.", explanation: "6/10 = 3/5" },
    { q: "What is (-2)⁴?", opts: ["-16", "-8", "8", "16"], ans: 3, topic: "Exponents", hint: "Even exponent → always positive result", explanation: "(-2)⁴ = 16. Even power → positive." },
    { q: "What is the prime factorization of 60?", opts: ["2²×3×5", "2×3×10", "4×15", "2³×5"], ans: 0, topic: "Primes & Factors", hint: "Start: 60 = 2 × 30 = 2 × 2 × 15...", explanation: "60 = 2² × 3 × 5" },
    { q: "What is 1/2 + 1/3 + 1/6?", opts: ["1/2", "2/3", "5/6", "1"], ans: 3, topic: "Fractions", hint: "LCD = 6. Convert: 3/6 + 2/6 + 1/6", explanation: "3/6 + 2/6 + 1/6 = 6/6 = 1" },
    { q: "What is 8% of 75?", opts: ["5", "6", "7", "8"], ans: 1, topic: "Percentages", hint: "0.08 × 75", explanation: "0.08 × 75 = 6" },
    { q: "Which is equal to 2⁻³?", opts: ["-8", "-6", "1/8", "1/6"], ans: 2, topic: "Exponents", hint: "Negative exponent: a⁻ⁿ = 1/aⁿ", explanation: "2⁻³ = 1/2³ = 1/8" },
    { q: "What is 3.6 ÷ 0.09?", opts: ["4", "40", "0.4", "400"], ans: 1, topic: "Decimals", hint: "Multiply both by 100: 360 ÷ 9", explanation: "3.6 ÷ 0.09 = 360 ÷ 9 = 40" },
    { q: "If x = -2, what is x³?", opts: ["6", "-6", "8", "-8"], ans: 3, topic: "Integers", hint: "Odd exponent preserves sign of negative", explanation: "(-2)³ = -8" },
    { q: "Simplify: (2/3)²", opts: ["4/3", "2/9", "4/9", "4/6"], ans: 2, topic: "Fractions", hint: "Square numerator and denominator separately", explanation: "(2/3)² = 4/9" },
    { q: "What is 17 mod 5?", opts: ["1", "2", "3", "4"], ans: 1, topic: "Integers", hint: "17 = 5 × 3 + ?", explanation: "17 = 5×3 + 2. Remainder = 2." },
    { q: "What is 40% of 40% of 200?", opts: ["16", "24", "32", "40"], ans: 2, topic: "Percentages", hint: "Step 1: 40% of 200 = 80. Step 2: 40% of 80.", explanation: "0.4 × 200 = 80. 0.4 × 80 = 32." },
    { q: "What is √(16/25)?", opts: ["4/25", "4/5", "8/5", "2/5"], ans: 1, topic: "Square Roots", hint: "√(a/b) = √a/√b", explanation: "√16/√25 = 4/5" },
    { q: "A car travels 120 miles in 2.5 hours. What is its average speed?", opts: ["42 mph", "46 mph", "48 mph", "50 mph"], ans: 2, topic: "Ratios", hint: "Speed = Distance ÷ Time", explanation: "120 ÷ 2.5 = 48 mph" },
    { q: "What is 7/12 + 5/8?", opts: ["12/20", "29/24", "1/2", "3/4"], ans: 1, topic: "Fractions", hint: "LCD(12,8) = 24", explanation: "14/24 + 15/24 = 29/24" },
    { q: "Evaluate: 3 + 4 × 2 - 1", opts: ["13", "12", "10", "9"], ans: 2, topic: "Order of Operations", hint: "PEMDAS: multiply first", explanation: "3 + 8 - 1 = 10" },
    { q: "Simplify: √50", opts: ["5√2", "25√2", "10√5", "5√10"], ans: 0, topic: "Square Roots", hint: "50 = 25 × 2. Pull out √25.", explanation: "√50 = √(25×2) = 5√2" },
    { q: "What is (-3)² - (-3)?", opts: ["6", "9", "12", "15"], ans: 2, topic: "Integers", hint: "9 - (-3) = 9 + 3", explanation: "9 + 3 = 12" },
    { q: "What is the reciprocal of 3/7?", opts: ["3/7", "-3/7", "7/3", "-7/3"], ans: 2, topic: "Fractions", hint: "Flip numerator and denominator", explanation: "Reciprocal of 3/7 = 7/3" },
    { q: "A bag has 3 red, 5 blue, 2 green balls. Probability of picking blue?", opts: ["1/2", "5/9", "5/10", "1/3"], ans: 2, topic: "Probability", hint: "P = favorable / total", explanation: "5 blue out of 10 total = 5/10 = 1/2" },
    { q: "What is the next prime after 13?", opts: ["14", "15", "17", "19"], ans: 2, topic: "Primes & Factors", hint: "14=2×7, 15=3×5. Check 17.", explanation: "17 is prime (no divisors except 1 and 17)." },
    { q: "What is 10% of 10% of 1000?", opts: ["1", "10", "100", "0.1"], ans: 1, topic: "Percentages", hint: "10% of 1000 = 100. Then 10% of that.", explanation: "100 × 0.1 = 10" },
  ],

  1: [
    { q: "Solve: 2x + 5 = 13", opts: ["x = 3", "x = 4", "x = 9", "x = 18"], ans: 1, topic: "Linear Equations", hint: "Subtract 5, then divide by 2", explanation: "2x = 8 → x = 4", steps: ["2x = 13 - 5 = 8", "x = 4"] },
    { q: "Solve: 3x - 7 = 14", opts: ["x = 3", "x = 5", "x = 7", "x = 9"], ans: 2, topic: "Linear Equations", hint: "Add 7 to both sides first", explanation: "3x = 21 → x = 7" },
    { q: "Simplify: 3x + 2x - x", opts: ["4x", "5x", "6x - x", "3x"], ans: 0, topic: "Linear Equations", hint: "Combine like terms: (3+2-1)x", explanation: "4x" },
    { q: "What is the slope of y = 3x - 5?", opts: ["-5", "3", "-3", "5"], ans: 1, topic: "Slope & Lines", hint: "In y = mx + b, m is the slope", explanation: "Slope = 3 (the coefficient of x)" },
    { q: "Solve: x/4 = 7", opts: ["x = 3", "x = 11", "x = 28", "x = 1.75"], ans: 2, topic: "Linear Equations", hint: "Multiply both sides by 4", explanation: "x = 28" },
    { q: "Expand: 3(x + 4)", opts: ["3x + 4", "3x + 7", "3x + 12", "x + 12"], ans: 2, topic: "Linear Equations", hint: "Distribute 3 to both terms", explanation: "3x + 12" },
    { q: "Solve: 5x + 2 = 3x + 10", opts: ["x = 2", "x = 4", "x = 6", "x = 8"], ans: 1, topic: "Linear Equations", hint: "Move x to one side, constants to the other", explanation: "2x = 8 → x = 4", steps: ["5x - 3x = 10 - 2", "2x = 8", "x = 4"] },
    { q: "What is the y-intercept of y = 2x + 7?", opts: ["2", "-2", "7", "-7"], ans: 2, topic: "Slope & Lines", hint: "In y = mx + b, b is the y-intercept", explanation: "y-intercept = 7 (set x=0)" },
    { q: "Simplify: 4(2x - 3) + 5", opts: ["8x - 7", "8x - 17", "8x + 7", "6x - 7"], ans: 0, topic: "Linear Equations", hint: "Distribute first: 8x - 12, then add 5", explanation: "8x - 12 + 5 = 8x - 7" },
    { q: "Solve: -3x = 18", opts: ["x = -6", "x = 6", "x = -54", "x = 15"], ans: 0, topic: "Linear Equations", hint: "Divide both sides by -3", explanation: "x = -6" },
    { q: "Factor: x² + 5x + 6", opts: ["(x+2)(x+3)", "(x+1)(x+6)", "(x+3)(x+3)", "(x-2)(x-3)"], ans: 0, topic: "Factoring", hint: "Find two numbers: product=6, sum=5", explanation: "2×3=6, 2+3=5. So (x+2)(x+3).", steps: ["Need: product=6, sum=5", "2 and 3 work", "(x+2)(x+3)"] },
    { q: "Solve the system: x + y = 5, x - y = 1", opts: ["x=2,y=3", "x=3,y=2", "x=4,y=1", "x=1,y=4"], ans: 1, topic: "Systems of Equations", hint: "Add equations to eliminate y", explanation: "2x=6, x=3. y=2.", steps: ["Add: 2x=6", "x=3", "y=5-3=2"] },
    { q: "What is the slope of a horizontal line?", opts: ["1", "-1", "0", "undefined"], ans: 2, topic: "Slope & Lines", hint: "Horizontal: no rise, so Δy=0", explanation: "Slope = 0" },
    { q: "Simplify: (x³)(x⁴)", opts: ["x⁷", "x¹²", "2x⁷", "x^34"], ans: 0, topic: "Exponent Rules", hint: "Same base: add exponents", explanation: "x^(3+4) = x⁷" },
    { q: "Solve: |x| = 9", opts: ["x = 9", "x = -9", "x = 9 or x = -9", "no solution"], ans: 2, topic: "Absolute Value", hint: "|x|=9 means x is 9 units from zero", explanation: "x = 9 or x = -9" },
    { q: "What is the slope between (2,3) and (6,11)?", opts: ["1", "2", "3", "4"], ans: 1, topic: "Slope & Lines", hint: "slope = (y₂-y₁)/(x₂-x₁)", explanation: "(11-3)/(6-2) = 8/4 = 2" },
    { q: "Solve: 2(x-3) = x + 5", opts: ["x = 8", "x = 11", "x = 1", "x = -1"], ans: 1, topic: "Linear Equations", hint: "Distribute left, collect x terms", explanation: "2x-6=x+5 → x=11" },
    { q: "Simplify: (2x²)³", opts: ["6x⁵", "8x⁶", "6x⁶", "8x⁵"], ans: 1, topic: "Exponent Rules", hint: "(ab)ⁿ = aⁿbⁿ", explanation: "2³·x^(2·3) = 8x⁶" },
    { q: "Factor: x² - 9", opts: ["(x-3)²", "(x+3)(x-3)", "(x-9)(x+1)", "(x+9)(x-1)"], ans: 1, topic: "Factoring", hint: "Difference of squares: a²-b²=(a+b)(a-b)", explanation: "(x+3)(x-3)" },
    { q: "Solve: x² = 25", opts: ["x = 5", "x = -5", "x = ±5", "x = ±25"], ans: 2, topic: "Factoring", hint: "Take ± square root of both sides", explanation: "x = ±5" },
    { q: "Equation of line slope 2 through (0,3)?", opts: ["y = 3x + 2", "y = 2x + 3", "y = 2x - 3", "y = 3x - 2"], ans: 1, topic: "Slope & Lines", hint: "y = mx + b. m=2, b=3.", explanation: "y = 2x + 3" },
    { q: "Solve: 3x/5 = 9", opts: ["x = 3", "x = 9", "x = 15", "x = 27"], ans: 2, topic: "Linear Equations", hint: "Multiply both sides by 5, then divide by 3", explanation: "3x=45 → x=15" },
    { q: "Simplify: (3x + 2)(x - 4)", opts: ["3x² - 10x - 8", "3x² - 12x - 8", "3x² + 10x - 8", "3x² - 10x + 8"], ans: 0, topic: "Factoring", hint: "FOIL: First, Outer, Inner, Last", explanation: "3x²-12x+2x-8 = 3x²-10x-8" },
    { q: "Solve: 4 - 2x > 10", opts: ["x > -3", "x < -3", "x > 3", "x < 3"], ans: 1, topic: "Inequalities", hint: "When dividing by negative, flip the inequality!", explanation: "-2x > 6 → x < -3", steps: ["-2x > 10-4 = 6", "Divide by -2 (flip!): x < -3"] },
    { q: "What is f(3) if f(x) = 2x² - x + 1?", opts: ["14", "16", "18", "20"], ans: 1, topic: "Functions", hint: "Plug in x=3", explanation: "2(9) - 3 + 1 = 16" },
    { q: "Solve: x² - 5x + 6 = 0", opts: ["x=1,x=6", "x=2,x=3", "x=-2,x=-3", "x=2,x=-3"], ans: 1, topic: "Factoring", hint: "Factor: numbers multiply to 6, add to -5", explanation: "(x-2)(x-3)=0 → x=2 or x=3" },
    { q: "Simplify: x⁴/x²", opts: ["x⁶", "x²", "x⁸", "1"], ans: 1, topic: "Exponent Rules", hint: "Divide same base: subtract exponents", explanation: "x^(4-2) = x²" },
    { q: "Domain of f(x) = 1/x?", opts: ["all reals", "x ≠ 0", "x > 0", "x ≥ 0"], ans: 1, topic: "Functions", hint: "What makes it undefined?", explanation: "Division by zero → x ≠ 0" },
    { q: "Solve: √x = 7", opts: ["x = 3.5", "x = 14", "x = 49", "x = 7"], ans: 2, topic: "Factoring", hint: "Square both sides", explanation: "x = 49" },
    { q: "Write in slope-intercept form: 2x - y = 4", opts: ["y = 2x - 4", "y = -2x + 4", "y = 2x + 4", "y = x - 4"], ans: 0, topic: "Slope & Lines", hint: "Solve for y", explanation: "y = 2x - 4" },
    { q: "Factor completely: 2x² - 8", opts: ["2(x²-4)", "2(x-2)(x+2)", "(2x-4)(x+2)", "2(x-4)"], ans: 1, topic: "Factoring", hint: "Factor out 2, then use difference of squares", explanation: "2(x²-4) = 2(x+2)(x-2)" },
    { q: "Solve: (x+2)² = 16", opts: ["x=2 or x=-6", "x=2 or x=6", "x=14 or x=-18", "x=4 or x=-4"], ans: 0, topic: "Factoring", hint: "x+2 = ±4", explanation: "x+2 = ±4 → x=2 or x=-6" },
    { q: "If f(x)=3x+1 and g(x)=x², what is f(g(2))?", opts: ["9", "13", "25", "49"], ans: 1, topic: "Functions", hint: "Find g(2) first, then plug into f", explanation: "g(2)=4. f(4)=13.", steps: ["g(2)=4", "f(4)=3(4)+1=13"] },
    { q: "Solve: |2x - 3| = 7", opts: ["x=5 or x=-2", "x=2 or x=-5", "x=5 only", "x=-2 only"], ans: 0, topic: "Absolute Value", hint: "Two cases: 2x-3=7 and 2x-3=-7", explanation: "x=5 or x=-2" },
    { q: "x-intercepts of y = x² - 4x + 3?", opts: ["x=1,x=3", "x=-1,x=-3", "x=0,x=4", "x=2,x=2"], ans: 0, topic: "Factoring", hint: "Factor and set each factor = 0", explanation: "(x-1)(x-3)=0 → x=1,3" },
    { q: "Solve: log₂(x) = 3", opts: ["x = 6", "x = 8", "x = 9", "x = 2/3"], ans: 1, topic: "Logarithms", hint: "log₂(x)=3 means 2³=x", explanation: "x = 2³ = 8" },
    { q: "Vertex of y = (x-3)² + 2?", opts: ["(3,2)", "(-3,2)", "(3,-2)", "(-3,-2)"], ans: 0, topic: "Factoring", hint: "Vertex form y=(x-h)²+k has vertex (h,k)", explanation: "Vertex = (3,2)" },
    { q: "Discriminant of x²-4x+5?", opts: ["-4", "4", "36", "-36"], ans: 0, topic: "Factoring", hint: "b²-4ac with a=1,b=-4,c=5", explanation: "16-20 = -4 (no real roots)" },
    { q: "Solve: e^x = 1", opts: ["x=0", "x=1", "x=e", "x=-1"], ans: 0, topic: "Logarithms", hint: "e⁰=1", explanation: "x=0 (anything to the 0 power = 1)" },
  ],

  2: [
    { q: "Simplify: (x²-9)/(x+3)", opts: ["x-3", "x+3", "(x-3)/(x+3)", "x²-3"], ans: 0, topic: "Rational Expressions", hint: "Factor x²-9 = (x+3)(x-3)", explanation: "Cancel (x+3): result = x-3" },
    { q: "Sum of arithmetic series: a₁=2, d=3, n=10?", opts: ["155", "160", "165", "170"], ans: 0, topic: "Sequences & Series", hint: "Sₙ = n/2(2a₁+(n-1)d)", explanation: "5(4+27) = 5×31 = 155" },
    { q: "Solve: log(x)+log(x-3)=1 (base 10)", opts: ["x=5", "x=2", "x=-2", "x=10"], ans: 0, topic: "Logarithms", hint: "log(a)+log(b)=log(ab). Then x(x-3)=10", explanation: "x²-3x-10=0 → (x-5)(x+2)=0 → x=5" },
    { q: "8th term of 3, 6, 12, 24...?", opts: ["192", "384", "256", "768"], ans: 1, topic: "Sequences & Series", hint: "Geometric: aₙ = 3·2^(n-1)", explanation: "a₈ = 3·2⁷ = 384" },
    { q: "Simplify: (3+2i)(1-i)", opts: ["5-i", "3-2i", "1+2i", "5+i"], ans: 0, topic: "Complex Numbers", hint: "FOIL, use i²=-1", explanation: "3-3i+2i-2i² = 3-i+2 = 5-i" },
    { q: "Asymptotes of y = 1/(x-2)?", opts: ["x=2, y=1", "x=2, y=0", "x=-2, y=0", "x=0, y=2"], ans: 1, topic: "Rational Expressions", hint: "VA: denominator=0. HA: degree comparison.", explanation: "VA: x=2. HA: y=0 (num degree < denom degree)." },
    { q: "Solve: 2^(x+1) = 32", opts: ["x=3", "x=4", "x=5", "x=6"], ans: 1, topic: "Logarithms", hint: "32 = 2⁵. Match exponents.", explanation: "x+1=5 → x=4" },
    { q: "What is |3+4i|?", opts: ["3", "4", "5", "7"], ans: 2, topic: "Complex Numbers", hint: "|a+bi| = √(a²+b²)", explanation: "√(9+16) = 5" },
    { q: "Solve: x⁴ - 5x² + 4 = 0", opts: ["x=±1,±4", "x=±1,±2", "x=1,2", "x=±2,±4"], ans: 1, topic: "Factoring", hint: "Let u=x²: u²-5u+4=(u-1)(u-4)", explanation: "x²=1 or x²=4 → x=±1,±2" },
    { q: "Expansion of (x+y)³?", opts: ["x³+y³", "x³+3x²y+3xy²+y³", "x³+3xy+y³", "3x²+3y²"], ans: 1, topic: "Combinatorics", hint: "Pascal's triangle row 3: 1,3,3,1", explanation: "x³+3x²y+3xy²+y³" },
    { q: "Ways to arrange 5 books?", opts: ["25", "60", "100", "120"], ans: 3, topic: "Combinatorics", hint: "5! = 5×4×3×2×1", explanation: "120" },
    { q: "What is ⁸C₃?", opts: ["24", "56", "112", "336"], ans: 1, topic: "Combinatorics", hint: "8!/(3!5!) = (8×7×6)/6", explanation: "56" },
    { q: "Solve: ln(x) = 3", opts: ["x=e³", "x=3e", "x=3", "x=9"], ans: 0, topic: "Logarithms", hint: "ln(x)=3 means e³=x", explanation: "x = e³" },
    { q: "Common ratio of 5, 15, 45...?", opts: ["3", "5", "10", "1/3"], ans: 0, topic: "Sequences & Series", hint: "Divide any term by previous", explanation: "15/5 = 3" },
    { q: "Simplify: i²⁵", opts: ["1", "-1", "i", "-i"], ans: 2, topic: "Complex Numbers", hint: "Powers of i cycle with period 4. 25 mod 4 = ?", explanation: "25 mod 4 = 1 → i¹ = i" },
    { q: "Sum of infinite series 1+1/2+1/4+...?", opts: ["1.5", "2", "2.5", "3"], ans: 1, topic: "Sequences & Series", hint: "S = a/(1-r), r=1/2", explanation: "1/(1-0.5) = 2" },
    { q: "Solve: x^(2/3) = 4", opts: ["x=6", "x=8", "x=12", "x=64"], ans: 1, topic: "Exponent Rules", hint: "Raise both sides to 3/2", explanation: "x = 4^(3/2) = 8" },
    { q: "Remainder of x³-2x+5 divided by (x-1)?", opts: ["2", "3", "4", "5"], ans: 2, topic: "Polynomial Division", hint: "Remainder theorem: plug in x=1", explanation: "f(1) = 1-2+5 = 4" },
    { q: "Inverse of f(x) = (x+1)/(x-1)?", opts: ["(x+1)/(x-1)", "(x-1)/(x+1)", "(1+x)/(x-1)", "(x-1)/(1-x)"], ans: 0, topic: "Functions", hint: "Swap x and y, solve for y", explanation: "It's self-inverse: (x+1)/(x-1)" },
    { q: "log₃(81) - log₃(9)?", opts: ["1", "2", "3", "4"], ans: 1, topic: "Logarithms", hint: "log(a)-log(b) = log(a/b)", explanation: "log₃(9) = 2" },
    { q: "Period of f(x) = sin(2x)?", opts: ["π/2", "π", "2π", "4π"], ans: 1, topic: "Trig Basics", hint: "Period = 2π/B where B is the coefficient of x", explanation: "2π/2 = π" },
    { q: "Real zeros of x³ - 6x² + 11x - 6?", opts: ["1,2,3", "1,2,6", "2,3,4", "-1,-2,-3"], ans: 0, topic: "Polynomial Division", hint: "Try rational roots: 1, 2, 3", explanation: "f(1)=0, f(2)=0, f(3)=0" },
    { q: "Amplitude of y = -3sin(x)?", opts: ["-3", "3", "π", "2π"], ans: 1, topic: "Trig Basics", hint: "Amplitude = |coefficient|, always positive", explanation: "|-3| = 3" },
    { q: "Evaluate: log₄(1/16)", opts: ["-4", "-2", "2", "4"], ans: 1, topic: "Logarithms", hint: "1/16 = 4⁻²", explanation: "log₄(4⁻²) = -2" },
    { q: "Vertex form of y = x²+6x+5?", opts: ["(x+3)²-4", "(x-3)²-4", "(x+3)²+4", "(x+6)²-4"], ans: 0, topic: "Factoring", hint: "Complete the square: half of 6 is 3", explanation: "(x+3)²-4" },
    { q: "Horizontal asymptote of f(x)=(3x²+1)/(x²-4)?", opts: ["y=0", "y=1", "y=3", "y=-3"], ans: 2, topic: "Rational Expressions", hint: "Same degree: ratio of leading coefficients", explanation: "3/1 = 3" },
    { q: "Solve: 4^x = 8", opts: ["x=1/2", "x=3/2", "x=2", "x=3"], ans: 1, topic: "Logarithms", hint: "Write as powers of 2: 2^(2x)=2³", explanation: "2x=3 → x=3/2" },
    { q: "Simplify: √(-36)", opts: ["6", "-6", "6i", "-6i"], ans: 2, topic: "Complex Numbers", hint: "√(-1) = i", explanation: "6i" },
    { q: "Sum of geometric series: a₁=3, r=2, n=5?", opts: ["93", "96", "99", "63"], ans: 0, topic: "Sequences & Series", hint: "Sₙ = a₁(rⁿ-1)/(r-1)", explanation: "3(31)/1 = 93" },
    { q: "Find: (x³-8)/(x-2)", opts: ["x²+4", "x²+2x+4", "x²-2x+4", "x²+2x-4"], ans: 1, topic: "Polynomial Division", hint: "x³-8 = (x-2)(x²+2x+4)", explanation: "x²+2x+4" },
    { q: "Phase shift of y=sin(x-π/3)?", opts: ["π/3 left", "π/3 right", "π/6 right", "π/6 left"], ans: 1, topic: "Trig Basics", hint: "y=sin(x-c): c>0 shifts right", explanation: "π/3 to the right" },
    { q: "How many ways to choose 2 from 8?", opts: ["16", "28", "56", "112"], ans: 1, topic: "Combinatorics", hint: "⁸C₂ = 8×7/2", explanation: "28" },
    { q: "Product of roots of 2x²-5x+3=0?", opts: ["5/2", "-5/2", "3/2", "-3/2"], ans: 2, topic: "Factoring", hint: "Vieta's: product = c/a", explanation: "3/2" },
    { q: "Solve: 2log(x) = log(4x)", opts: ["x=0", "x=4", "x=2", "x=16"], ans: 1, topic: "Logarithms", hint: "2log(x) = log(x²). Equate arguments.", explanation: "x²=4x → x=4" },
  ],

  3: [
    { q: "Area of triangle with base 8 and height 5?", opts: ["20", "40", "13", "80"], ans: 0, topic: "Area & Volume", hint: "A = (1/2)bh", explanation: "(1/2)(8)(5) = 20" },
    { q: "Sum of interior angles of a pentagon?", opts: ["360°", "450°", "540°", "720°"], ans: 2, topic: "Proofs", hint: "(n-2)×180°", explanation: "3×180° = 540°" },
    { q: "Right triangle legs 3 and 4. Hypotenuse?", opts: ["5", "6", "7", "√7"], ans: 0, topic: "Triangles", hint: "a²+b²=c²", explanation: "9+16=25 → c=5" },
    { q: "Circumference of circle with radius 6?", opts: ["6π", "12π", "36π", "3π"], ans: 1, topic: "Circles", hint: "C = 2πr", explanation: "2π(6) = 12π" },
    { q: "Alternate interior angles (parallel lines cut by transversal) are:", opts: ["supplementary", "complementary", "equal", "vertical"], ans: 2, topic: "Proofs", hint: "Parallel lines theorem", explanation: "Alternate interior angles are equal." },
    { q: "Area of circle with diameter 10?", opts: ["10π", "25π", "50π", "100π"], ans: 1, topic: "Circles", hint: "r = d/2 = 5. A = πr²", explanation: "π(25) = 25π" },
    { q: "Rectangle: perimeter 24, length 8. Width?", opts: ["3", "4", "6", "8"], ans: 1, topic: "Area & Volume", hint: "P = 2l+2w", explanation: "16+2w=24 → w=4" },
    { q: "Triangle: angle A=50°, B=70°. Find C.", opts: ["40°", "50°", "60°", "70°"], ans: 2, topic: "Triangles", hint: "Sum of angles = 180°", explanation: "180-50-70 = 60°" },
    { q: "Volume of cube with side 4?", opts: ["12", "16", "48", "64"], ans: 3, topic: "Area & Volume", hint: "V = s³", explanation: "4³ = 64" },
    { q: "Midpoint of (2,4) and (8,10)?", opts: ["(4,6)", "(5,7)", "(3,5)", "(6,8)"], ans: 1, topic: "Coordinate Geometry", hint: "Average x, average y", explanation: "(5,7)" },
    { q: "Distance between (1,2) and (4,6)?", opts: ["3", "4", "5", "6"], ans: 2, topic: "Coordinate Geometry", hint: "√((Δx)²+(Δy)²)", explanation: "√(9+16) = 5" },
    { q: "Similar triangles ratio 2:3, smaller area 8. Larger area?", opts: ["12", "16", "18", "24"], ans: 2, topic: "Congruence & Similarity", hint: "Area ratio = (side ratio)² = 4:9", explanation: "8×(9/4) = 18" },
    { q: "What is tan(45°)?", opts: ["0", "1/2", "1", "√2"], ans: 2, topic: "Triangles", hint: "45-45-90 triangle: legs equal", explanation: "tan(45°) = 1" },
    { q: "Arc with central angle 90° and radius 4: arc length?", opts: ["π", "2π", "4π", "8π"], ans: 1, topic: "Circles", hint: "Arc = (θ/360)×2πr", explanation: "(1/4)(8π) = 2π" },
    { q: "Area of trapezoid: bases 6 and 10, height 4?", opts: ["24", "32", "40", "48"], ans: 1, topic: "Area & Volume", hint: "A = (b₁+b₂)/2 × h", explanation: "(16/2)(4) = 32" },
    { q: "30-60-90 triangle, hypotenuse 10. Shorter leg?", opts: ["5", "5√3", "5√2", "10√3"], ans: 0, topic: "Triangles", hint: "Ratios: 1:√3:2. Shorter = hyp/2", explanation: "10/2 = 5" },
    { q: "Slope perpendicular to y = 2x + 1?", opts: ["2", "-2", "1/2", "-1/2"], ans: 3, topic: "Coordinate Geometry", hint: "Perpendicular slopes: negative reciprocals", explanation: "-1/2" },
    { q: "What is sin(30°)?", opts: ["√3/2", "1/2", "√2/2", "1"], ans: 1, topic: "Triangles", hint: "Memorize: sin30=1/2, sin45=√2/2, sin60=√3/2", explanation: "1/2" },
    { q: "Cylinder radius 3, height 5. Volume?", opts: ["15π", "30π", "45π", "90π"], ans: 2, topic: "Area & Volume", hint: "V = πr²h", explanation: "π(9)(5) = 45π" },
    { q: "Exterior angle of regular hexagon?", opts: ["45°", "60°", "72°", "90°"], ans: 1, topic: "Proofs", hint: "Exterior = 360°/n", explanation: "360/6 = 60°" },
    { q: "Two chords intersect: segments 3,4 and 2,x. Find x.", opts: ["5", "6", "7", "8"], ans: 1, topic: "Circles", hint: "Chord-chord: product of segments equal", explanation: "3×4=2×x → x=6" },
    { q: "Equation of circle centered at (2,-3), radius 5?", opts: ["(x-2)²+(y+3)²=25", "(x+2)²+(y-3)²=25", "(x-2)²+(y+3)²=5", "(x+2)²+(y-3)²=5"], ans: 0, topic: "Circles", hint: "(x-h)²+(y-k)²=r²", explanation: "(x-2)²+(y+3)²=25" },
    { q: "Area of equilateral triangle with side 4?", opts: ["4√3", "8√3", "4", "16√3"], ans: 0, topic: "Triangles", hint: "A = (√3/4)s²", explanation: "(√3/4)(16) = 4√3" },
    { q: "Supplementary angle to 35°?", opts: ["55°", "65°", "145°", "155°"], ans: 2, topic: "Proofs", hint: "Supplementary = sums to 180°", explanation: "180-35 = 145°" },
    { q: "Sphere radius 3. Surface area?", opts: ["9π", "12π", "36π", "108π"], ans: 2, topic: "Area & Volume", hint: "SA = 4πr²", explanation: "4π(9) = 36π" },
  ],

  4: [
    { q: "What is sin²(x) + cos²(x)?", opts: ["0", "1", "2", "sin(2x)"], ans: 1, topic: "Trig Identities", hint: "The fundamental Pythagorean identity", explanation: "sin²x + cos²x = 1 always." },
    { q: "What is lim(x→0) sin(x)/x?", opts: ["0", "∞", "1", "π"], ans: 2, topic: "Limits", hint: "Classic limit — memorize this", explanation: "= 1. Fundamental calculus result." },
    { q: "Convert 150° to radians.", opts: ["π/3", "2π/3", "5π/6", "3π/4"], ans: 2, topic: "Trig Functions", hint: "Multiply by π/180", explanation: "150×π/180 = 5π/6" },
    { q: "Period of tan(x)?", opts: ["π/2", "π", "2π", "4π"], ans: 1, topic: "Trig Functions", hint: "Tangent repeats twice as fast as sin/cos", explanation: "π" },
    { q: "Focus of parabola y = x²?", opts: ["(0,0)", "(0,1/4)", "(0,1)", "(1/4,0)"], ans: 1, topic: "Conic Sections", hint: "y=x²: 4p=1 → p=1/4", explanation: "Focus = (0, 1/4)" },
    { q: "Inverse of sin(x)?", opts: ["1/sin(x)", "cos(x)", "arcsin(x)", "-sin(x)"], ans: 2, topic: "Trig Functions", hint: "arcsin undoes sin. Don't confuse with csc(x)=1/sin(x).", explanation: "arcsin(x)" },
    { q: "lim(x→2) (x²-4)/(x-2)?", opts: ["0", "2", "4", "undefined"], ans: 2, topic: "Limits", hint: "Factor x²-4 = (x+2)(x-2), cancel (x-2)", explanation: "= x+2 at x=2 → 4" },
    { q: "Ellipse equation: semi-axes a=5, b=3?", opts: ["x²/5+y²/3=1", "x²/25+y²/9=1", "x²/3+y²/5=1", "x²/9+y²/25=1"], ans: 1, topic: "Conic Sections", hint: "x²/a²+y²/b²=1", explanation: "x²/25+y²/9=1" },
    { q: "cos(2x) in terms of cos(x)?", opts: ["2cos(x)", "cos²(x)-sin²(x)", "2cos²(x)-1", "1-2sin²(x)"], ans: 2, topic: "Trig Identities", hint: "Double angle identity", explanation: "2cos²(x)-1 (also equals cos²x-sin²x)" },
    { q: "Amplitude of y = 4sin(3x)?", opts: ["3", "4", "12", "π"], ans: 1, topic: "Trig Functions", hint: "Amplitude = |leading coefficient|", explanation: "4 (the 3 affects period only)" },
    { q: "lim(x→∞) (3x²+1)/(x²-4)?", opts: ["0", "1", "3", "∞"], ans: 2, topic: "Limits", hint: "Divide by x², highest power. Leading terms dominate.", explanation: "3/1 = 3" },
    { q: "Polar form of (0,-3)?", opts: ["(3,π/2)", "(3,-π/2)", "(3,π)", "(-3,0)"], ans: 1, topic: "Polar Coordinates", hint: "Negative y-axis: θ = -π/2", explanation: "(3, -π/2)" },
    { q: "What is log_b(b)?", opts: ["0", "1", "b", "1/b"], ans: 1, topic: "Logarithms", hint: "b to what power = b? → 1", explanation: "logₐ(a) = 1" },
    { q: "A function is even if:", opts: ["f(-x)=-f(x)", "f(-x)=f(x)", "f(x)=f(1/x)", "f(x)≥0"], ans: 1, topic: "Functions", hint: "Even = symmetric about y-axis", explanation: "f(-x) = f(x)" },
    { q: "Range of y = sin(x)?", opts: ["[0,1]", "[-1,1]", "(0,∞)", "all reals"], ans: 1, topic: "Trig Functions", hint: "Sine oscillates between -1 and 1", explanation: "[-1, 1]" },
    { q: "Simplify: sin(x)/cos(x)", opts: ["1", "csc(x)", "tan(x)", "sec(x)"], ans: 2, topic: "Trig Identities", hint: "Definition of tangent", explanation: "tan(x)" },
    { q: "Asymptote of y = ln(x)?", opts: ["y=0", "x=0", "x=1", "y=1"], ans: 1, topic: "Limits", hint: "ln(x) → -∞ as x → 0⁺", explanation: "x=0 vertical asymptote" },
    { q: "Convert 3π/4 to degrees.", opts: ["105°", "120°", "135°", "150°"], ans: 2, topic: "Trig Functions", hint: "Multiply by 180/π", explanation: "3×45 = 135°" },
    { q: "Eccentricity of a circle?", opts: ["0", "1", ">1", "<0"], ans: 0, topic: "Conic Sections", hint: "Perfect symmetry → no eccentricity", explanation: "0" },
    { q: "Is f(x) = x³ odd, even, or neither?", opts: ["even", "odd", "neither", "both"], ans: 1, topic: "Functions", hint: "f(-x) = (-x)³ = ?", explanation: "-x³ = -f(x) → odd" },
    { q: "Solutions to cos(x)=0 on [0,2π)?", opts: ["x=π/4,5π/4", "x=π/2,3π/2", "x=0,π", "x=π/3,2π/3"], ans: 1, topic: "Trig Functions", hint: "Where is cosine zero on unit circle?", explanation: "π/2 and 3π/2" },
    { q: "VAs of f(x)=(x+1)/(x²-1)?", opts: ["x=1 only", "x=-1 only", "x=1 and x=-1", "x=0"], ans: 0, topic: "Rational Expressions", hint: "Cancel common factors first. x=-1 is a hole.", explanation: "x=1 only (x=-1 is a hole)" },
    { q: "Exact value of sin(π/4)?", opts: ["1/2", "√3/2", "√2/2", "1"], ans: 2, topic: "Trig Functions", hint: "45° on unit circle", explanation: "√2/2" },
    { q: "lim(x→0) (1-cos x)/x?", opts: ["0", "1", "∞", "1/2"], ans: 0, topic: "Limits", hint: "Numerator → 0 faster than x → 0", explanation: "= 0" },
  ],

  5: [
    { q: "What is d/dx[x³]?", opts: ["x²", "3x²", "3x³", "x⁴/4"], ans: 1, topic: "Derivatives", hint: "Power rule: d/dx[xⁿ]=nxⁿ⁻¹", explanation: "3x²" },
    { q: "What is d/dx[sin(x)]?", opts: ["sin(x)", "-sin(x)", "cos(x)", "-cos(x)"], ans: 2, topic: "Derivatives", hint: "Derivative of sine is cosine", explanation: "cos(x)" },
    { q: "What is ∫ 2x dx?", opts: ["x + C", "x² + C", "2 + C", "2x² + C"], ans: 1, topic: "Integrals", hint: "Power rule for integration", explanation: "x² + C" },
    { q: "What is lim(x→0) sin(x)/x?", opts: ["0", "∞", "1", "π"], ans: 2, topic: "Limits", hint: "Classic limit", explanation: "= 1" },
    { q: "Find d/dx[sin(x²)] using chain rule", opts: ["cos(x²)", "2x·cos(x²)", "-cos(x²)", "2sin(x)"], ans: 1, topic: "Chain Rule", hint: "Outer: sin→cos. Inner: x²→2x", explanation: "2x·cos(x²)", steps: ["Outer: d/dx[sin(u)] = cos(u)", "Inner: u=x², du/dx=2x", "Chain: cos(x²)·2x"] },
    { q: "What is d/dx[e^x]?", opts: ["e^x·x", "e^(x-1)", "xe^(x-1)", "e^x"], ans: 3, topic: "Derivatives", hint: "e^x is its own derivative!", explanation: "e^x" },
    { q: "What is d/dx[ln(x)]?", opts: ["1/x", "ln(x)", "e^x", "x·ln(x)"], ans: 0, topic: "Derivatives", hint: "Standard derivative", explanation: "1/x" },
    { q: "Critical points of f(x) = x³ - 3x?", opts: ["x=0", "x=±1", "x=±√3", "x=3"], ans: 1, topic: "Optimization", hint: "Set f'(x)=0", explanation: "f'=3x²-3=0 → x=±1", steps: ["f'(x) = 3x²-3", "3x²=3 → x=±1"] },
    { q: "Fundamental Theorem of Calculus states:", opts: ["∫f'dx=f(x)+C", "d/dx[∫ₐˣf(t)dt]=f(x)", "∫ₐᵇf dx=F(b)-F(a)", "Both B and C"], ans: 3, topic: "Fundamental Theorem", hint: "FTC has two parts", explanation: "Both Part 1 (derivative of integral) and Part 2 (evaluation formula)." },
    { q: "What is ∫ cos(x) dx?", opts: ["-sin(x)+C", "sin(x)+C", "-cos(x)+C", "tan(x)+C"], ans: 1, topic: "Integrals", hint: "What has derivative = cos(x)?", explanation: "sin(x) + C" },
    { q: "Find d/dx[x²·e^x]", opts: ["2x·e^x", "x²·e^x", "2x·e^x+x²·e^x", "e^x(2x-x²)"], ans: 2, topic: "Derivatives", hint: "Product rule: (fg)'=f'g+fg'", explanation: "2xe^x + x²e^x" },
    { q: "Derivative of arctan(x)?", opts: ["1/(1+x²)", "1/√(1-x²)", "tan(x)", "1/x"], ans: 0, topic: "Derivatives", hint: "Standard result to memorize", explanation: "1/(1+x²)" },
    { q: "Evaluate: ∫₀¹ x² dx", opts: ["1/2", "1/3", "1/4", "1"], ans: 1, topic: "Integrals", hint: "[x³/3] from 0 to 1", explanation: "1/3" },
    { q: "What is ∫ 1/x dx?", opts: ["x⁻²+C", "ln|x|+C", "1/x²+C", "e^x+C"], ans: 1, topic: "Integrals", hint: "Power rule fails at n=-1. Use ln.", explanation: "ln|x| + C" },
    { q: "Slope of y=x² at x=3?", opts: ["3", "6", "9", "12"], ans: 1, topic: "Derivatives", hint: "Differentiate, then evaluate at x=3", explanation: "y'=2x. At x=3: 6." },
    { q: "Mean Value Theorem:", opts: ["f'(c)=(f(b)-f(a))/(b-a) for some c∈(a,b)", "every continuous function is differentiable", "f(c)=(f(a)+f(b))/2", "if f'(c)=0, c is max"], ans: 0, topic: "Derivatives", hint: "Instantaneous rate = average rate somewhere", explanation: "f'(c) = (f(b)-f(a))/(b-a)" },
    { q: "What is d/dx[cos(x)]?", opts: ["sin(x)", "-sin(x)", "cos(x)", "-cos(x)"], ans: 1, topic: "Derivatives", hint: "Cosine's derivative has a negative sign", explanation: "-sin(x)" },
    { q: "Substitution: ∫ 2x·cos(x²) dx", opts: ["sin(x²)+C", "2sin(x)+C", "cos(x²)+C", "-sin(x²)+C"], ans: 0, topic: "Integrals", hint: "u=x², du=2x dx", explanation: "sin(x²) + C", steps: ["u=x², du=2x dx", "∫cos(u)du = sin(u)+C", "= sin(x²)+C"] },
    { q: "Evaluate: ∫₁² (1/x) dx", opts: ["0", "ln(2)", "1", "2"], ans: 1, topic: "Integrals", hint: "[ln|x|] from 1 to 2", explanation: "ln(2)-ln(1) = ln(2)" },
    { q: "Absolute max of f(x)=-x²+4x on [0,5]?", opts: ["3", "4", "5", "0"], ans: 1, topic: "Optimization", hint: "f'(x)=0, check critical points and endpoints", explanation: "f'=-2x+4=0→x=2. f(2)=4. Max=4.", steps: ["f'(x)=-2x+4=0 → x=2", "f(2)=-4+8=4", "f(0)=0, f(5)=-5", "Max is 4"] },
    { q: "What is d²/dx²[sin(x)]?", opts: ["cos(x)", "-cos(x)", "sin(x)", "-sin(x)"], ans: 3, topic: "Derivatives", hint: "Differentiate cos(x) to get second derivative", explanation: "d/dx[cos(x)] = -sin(x)" },
    { q: "Find: ∫ sec²(x) dx", opts: ["sec(x)tan(x)+C", "tan(x)+C", "2sec(x)+C", "cot(x)+C"], ans: 1, topic: "Integrals", hint: "d/dx[tan(x)] = sec²(x)", explanation: "tan(x)+C" },
    { q: "d/dx[a^x] where a is constant?", opts: ["xa^(x-1)", "a^x", "a^x·ln(a)", "a^x/ln(a)"], ans: 2, topic: "Derivatives", hint: "For e^x: ln(e)=1 so works out to e^x", explanation: "a^x·ln(a)" },
    { q: "Average value of f(x)=x² on [0,3]?", opts: ["2", "3", "4", "9"], ans: 1, topic: "Integrals", hint: "(1/(b-a))∫ₐᵇ f dx", explanation: "(1/3)[x³/3]₀³ = (1/3)(9) = 3" },
    { q: "What is ∫ tan(x) dx?", opts: ["sec²(x)+C", "ln|cos(x)|+C", "-ln|cos(x)|+C", "ln|sin(x)|+C"], ans: 2, topic: "Integrals", hint: "u=cos(x), du=-sin(x)dx", explanation: "-ln|cos(x)| + C" },
  ],

  6: [
    { q: "∫ x·ln(x) dx?", opts: ["x²ln(x)/2-x²/4+C", "x²ln(x)/2+C", "ln(x)/x+C", "x·ln(x)-x+C"], ans: 0, topic: "Integration Techniques", hint: "IBP: u=ln(x), dv=x dx", explanation: "x²ln(x)/2 - x²/4 + C", steps: ["u=ln(x), dv=x dx", "du=1/x dx, v=x²/2", "uv-∫v du = x²ln(x)/2 - x²/4+C"] },
    { q: "Test for Σ 1/n²?", opts: ["ratio test", "root test", "p-series test", "divergence test"], ans: 2, topic: "Series & Convergence", hint: "Σ 1/nᵖ is a p-series", explanation: "p-series with p=2>1 → converges" },
    { q: "Taylor series for e^x?", opts: ["Σ x^n/n!", "Σ x^n", "Σ (-1)^n x^n/n!", "Σ x^n/n"], ans: 0, topic: "Taylor Series", hint: "All derivatives of e^x equal e^x, evaluated at 0=1", explanation: "Σ xⁿ/n! = 1+x+x²/2!+..." },
    { q: "Does Σ 1/n converge?", opts: ["yes", "no, it diverges", "depends on starting index", "conditionally converges"], ans: 1, topic: "Series & Convergence", hint: "Harmonic series — famous divergent series", explanation: "Diverges (p=1, not >1)" },
    { q: "Volume of revolution (disk method)?", opts: ["π∫[f(x)]²dx", "2π∫x·f(x)dx", "∫[f(x)]²dx", "π∫f(x)dx"], ans: 0, topic: "Applications of Integration", hint: "Each disk has area πr²=π[f(x)]²", explanation: "π∫ₐᵇ[f(x)]²dx" },
    { q: "Maclaurin series for sin(x)?", opts: ["Σ(-1)^n x^(2n)/(2n)!", "Σ(-1)^n x^(2n+1)/(2n+1)!", "Σ x^n/n!", "Σ(-1)^n x^n/n!"], ans: 1, topic: "Taylor Series", hint: "Odd powers only, alternating signs", explanation: "x-x³/3!+x⁵/5!-... = Σ(-1)ⁿx^(2n+1)/(2n+1)!" },
    { q: "∫ 1/(x²-1) dx?", opts: ["(1/2)ln|(x-1)/(x+1)|+C", "arctan(x)+C", "ln|x²-1|+C", "1/(2x)+C"], ans: 0, topic: "Integration Techniques", hint: "Partial fractions: 1/(x²-1)=A/(x-1)+B/(x+1)", explanation: "(1/2)ln|(x-1)/(x+1)|+C" },
    { q: "Ratio test: convergence condition?", opts: ["lim|aₙ₊₁/aₙ|<1", "lim|aₙ₊₁/aₙ|>1", "lim|aₙ₊₁/aₙ|=1", "lim aₙ=0"], ans: 0, topic: "Series & Convergence", hint: "L<1→converge, L>1→diverge, L=1→inconclusive", explanation: "Absolute convergence if L < 1" },
    { q: "∫₀^∞ e^(-x) dx?", opts: ["0", "1", "e", "∞"], ans: 1, topic: "Applications of Integration", hint: "[-e^(-x)]₀^∞", explanation: "0-(-1) = 1" },
    { q: "Area between y=x² and y=x?", opts: ["1/3", "1/6", "1/2", "1/4"], ans: 1, topic: "Applications of Integration", hint: "Intersect at 0,1. ∫₀¹(x-x²)dx", explanation: "[x²/2-x³/3]₀¹ = 1/2-1/3 = 1/6" },
    { q: "Shell method formula?", opts: ["2π∫x·f(x)dx", "π∫[f(x)]²dx", "∫f(x)dx", "π∫[f(x)-g(x)]²dx"], ans: 0, topic: "Applications of Integration", hint: "Shell: circumference 2πx, height f(x)", explanation: "2π∫ₐᵇ x·f(x) dx" },
    { q: "Arc length formula for y=f(x)?", opts: ["∫√(1+[f'(x)]²)dx", "∫√(1+[f(x)]²)dx", "∫[f'(x)]²dx", "∫f'(x)dx"], ans: 0, topic: "Applications of Integration", hint: "Involves derivative, not function", explanation: "∫ₐᵇ√(1+[f'(x)]²)dx" },
    { q: "Does Σ(-1)^n/n converge?", opts: ["no", "yes, absolutely", "yes, conditionally", "only if n is even"], ans: 2, topic: "Series & Convergence", hint: "AST says yes. But Σ1/n diverges → not absolute.", explanation: "Converges conditionally" },
    { q: "Power series for 1/(1-x), |x|<1?", opts: ["Σ xⁿ", "Σ(-1)^n xⁿ", "Σ xⁿ/n!", "Σ nxⁿ"], ans: 0, topic: "Taylor Series", hint: "Geometric series: 1+x+x²+...", explanation: "Σ xⁿ" },
    { q: "∫ sin²(x) dx?", opts: ["x/2-sin(2x)/4+C", "cos²(x)/2+C", "-cos(2x)/2+C", "sin(2x)/2+C"], ans: 0, topic: "Integration Techniques", hint: "Use sin²x=(1-cos2x)/2", explanation: "x/2 - sin(2x)/4 + C" },
    { q: "Radius of convergence of Σ xⁿ/n?", opts: ["0", "1", "e", "∞"], ans: 1, topic: "Series & Convergence", hint: "Ratio test: limit = |x|", explanation: "R = 1" },
    { q: "Integration by parts formula?", opts: ["∫u dv=uv-∫v du", "∫u dv=uv+∫v du", "∫uv dx=u'v-uv'", "∫f(g(x))=f(g(x))g'(x)"], ans: 0, topic: "Integration Techniques", hint: "Derived from product rule", explanation: "∫u dv = uv - ∫v du" },
    { q: "∫ sec(x) dx?", opts: ["ln|sec(x)+tan(x)|+C", "tan(x)+C", "sec(x)tan(x)+C", "ln|cos(x)|+C"], ans: 0, topic: "Integration Techniques", hint: "Multiply by (sec x+tan x)/(sec x+tan x)", explanation: "ln|sec(x)+tan(x)|+C" },
    { q: "Does Σ(-1)^n/n² converge absolutely?", opts: ["no", "yes", "conditionally only", "diverges"], ans: 1, topic: "Series & Convergence", hint: "Σ|aₙ|=Σ1/n²: convergent p-series", explanation: "Yes, absolutely (p=2>1)" },
    { q: "Maclaurin series for cos(x)?", opts: ["Σ(-1)^n x^(2n+1)/(2n+1)!", "Σ(-1)^n x^(2n)/(2n)!", "Σ x^(2n)/(2n)!", "Σ(-1)^n x^n/(2n)!"], ans: 1, topic: "Taylor Series", hint: "Even powers only, alternating signs", explanation: "1-x²/2!+x⁴/4!-... = Σ(-1)ⁿx^(2n)/(2n)!" },
    { q: "Evaluate: ∫₀¹ x·e^x dx", opts: ["1", "e-1", "e", "e+1"], ans: 0, topic: "Integration Techniques", hint: "IBP: u=x, dv=e^x dx", explanation: "= 1", steps: ["u=x, v=e^x", "[xe^x]₀¹ - ∫₀¹e^x dx", "= e - (e-1) = 1"] },
    { q: "∫₁^∞ 1/x² dx?", opts: ["∞", "0", "1", "2"], ans: 2, topic: "Applications of Integration", hint: "[-1/x]₁^∞", explanation: "0-(-1) = 1" },
    { q: "d/dx[∫_{x}^{x²} sin(t²) dt]?", opts: ["2x·sin(x⁴)-sin(x²)", "sin(x⁴)-sin(x²)", "2x·sin(x⁴)", "sin(x²)"], ans: 0, topic: "Fundamental Theorem", hint: "FTC with chain rule on both bounds", explanation: "2x·sin(x⁴) - sin(x²)" },
    { q: "Absolute convergence means:", opts: ["Σ|aₙ| converges", "Σaₙ converges", "aₙ→0", "|aₙ|<1"], ans: 0, topic: "Series & Convergence", hint: "Stronger than regular convergence", explanation: "Σ|aₙ| converges" },
    { q: "Solve ODE: dy/dx = y", opts: ["y=x+C", "y=Ce^x", "y=e^(x+C)", "y=x·e^C"], ans: 1, topic: "Integration Techniques", hint: "Separate: dy/y = dx. Integrate.", explanation: "y = Ce^x" },
    { q: "∫ cos³(x) dx?", opts: ["sin(x)-sin³(x)/3+C", "3cos²(x)+C", "sin(x)/3+C", "cos²(x)sin(x)/3+C"], ans: 0, topic: "Integration Techniques", hint: "Write cos³x = cos(x)(1-sin²x), u=sin(x)", explanation: "sin(x) - sin³(x)/3 + C" },
  ]
};

module.exports = { questions, LEVELS, LEVEL_NAMES, TOPIC_LESSON_MAP };
