// APEX MATH — Adaptive Question Bank
// 7 levels, 50+ questions per level, randomized variants

const LEVELS = {
  ARITHMETIC: 0,
  EARLY_ALGEBRA: 1,
  ADVANCED_ALGEBRA: 2,
  GEOMETRY: 3,
  PRECALC: 4,
  CALC_INTRO: 5,
  CALC_ADVANCED: 6
};

const LEVEL_NAMES = [
  'Arithmetic',
  'Early Algebra',
  'Advanced Algebra',
  'Geometry',
  'Pre-Calculus',
  'Calculus I',
  'Calculus II'
];

const questions = {
  0: [ // ARITHMETIC
    { q: "What is 17 × 8?", opts: ["126", "136", "144", "156"], ans: 1 },
    { q: "What is 144 ÷ 12?", opts: ["10", "11", "12", "13"], ans: 2 },
    { q: "What is 3/4 + 1/3?", opts: ["4/7", "13/12", "5/7", "1/2"], ans: 1 },
    { q: "What is 2/5 × 5/6?", opts: ["1/3", "7/11", "1/4", "10/30"], ans: 0 },
    { q: "What is 15% of 200?", opts: ["20", "25", "30", "35"], ans: 2 },
    { q: "What is 3² + 4²?", opts: ["14", "25", "49", "7"], ans: 1 },
    { q: "Simplify: 48/64", opts: ["2/3", "3/4", "4/5", "6/8"], ans: 1 },
    { q: "What is 0.25 × 0.4?", opts: ["0.1", "0.01", "1.0", "0.065"], ans: 0 },
    { q: "What is the LCM of 4 and 6?", opts: ["8", "10", "12", "24"], ans: 2 },
    { q: "What is the GCF of 24 and 36?", opts: ["6", "8", "12", "18"], ans: 2 },
    { q: "Convert 3/8 to a decimal.", opts: ["0.325", "0.375", "0.425", "0.275"], ans: 1 },
    { q: "What is 2³ × 2²?", opts: ["2⁵", "2⁶", "4⁵", "2⁴"], ans: 0 },
    { q: "What is (-3) × (-4)?", opts: ["-12", "-7", "7", "12"], ans: 3 },
    { q: "What is 5! (5 factorial)?", opts: ["25", "60", "100", "120"], ans: 3 },
    { q: "What is 7/8 - 1/4?", opts: ["5/8", "6/8", "3/4", "1/2"], ans: 0 },
    { q: "What is 1000 × 0.001?", opts: ["0.1", "1", "10", "100"], ans: 1 },
    { q: "What is √144?", opts: ["11", "12", "13", "14"], ans: 1 },
    { q: "What is 30% of 150?", opts: ["35", "40", "45", "50"], ans: 2 },
    { q: "What is (-5) + 8 - 3?", opts: ["0", "1", "6", "-6"], ans: 0 },
    { q: "Which is largest: 3/5, 5/8, 7/10, 2/3?", opts: ["3/5", "5/8", "7/10", "2/3"], ans: 2 },
    { q: "What is 2.5² ?", opts: ["5", "5.25", "6", "6.25"], ans: 3 },
    { q: "What is 4/9 ÷ 2/3?", opts: ["8/27", "2/3", "6/9", "2/9"], ans: 1 },
    { q: "If a shirt costs $40 and is 25% off, what is the sale price?", opts: ["$25", "$28", "$30", "$32"], ans: 2 },
    { q: "What is the absolute value of -17?", opts: ["-17", "0", "17", "289"], ans: 2 },
    { q: "Round 3.748 to the nearest tenth.", opts: ["3.7", "3.74", "3.75", "3.8"], ans: 3 },
    { q: "What is 12³?", opts: ["36", "144", "1,728", "1,440"], ans: 2 },
    { q: "What is 5/6 of 48?", opts: ["36", "38", "40", "42"], ans: 2 },
    { q: "A ratio is 3:5. If the first part is 12, what is the second?", opts: ["15", "18", "20", "25"], ans: 2 },
    { q: "What is 0.6 as a fraction in lowest terms?", opts: ["6/10", "3/5", "2/3", "60/100"], ans: 1 },
    { q: "What is (-2)⁴?", opts: ["-16", "-8", "8", "16"], ans: 3 },
    { q: "What is the prime factorization of 60?", opts: ["2²×3×5", "2×3×10", "4×15", "2³×5"], ans: 0 },
    { q: "What is 1/2 + 1/3 + 1/6?", opts: ["1/2", "2/3", "5/6", "1"], ans: 3 },
    { q: "What is 8% of 75?", opts: ["5", "6", "7", "8"], ans: 1 },
    { q: "Which is equal to 2⁻³?", opts: ["-8", "-6", "1/8", "1/6"], ans: 2 },
    { q: "What is 3.6 ÷ 0.09?", opts: ["4", "40", "0.4", "400"], ans: 1 },
    { q: "If x = -2, what is x³?", opts: ["6", "-6", "8", "-8"], ans: 3 },
    { q: "Simplify: (2/3)²", opts: ["4/3", "2/9", "4/9", "4/6"], ans: 2 },
    { q: "What is 17 mod 5?", opts: ["1", "2", "3", "4"], ans: 1 },
    { q: "What is 40% of 40% of 200?", opts: ["16", "24", "32", "40"], ans: 2 },
    { q: "What is √(16/25)?", opts: ["4/25", "4/5", "8/5", "2/5"], ans: 1 },
    { q: "A car travels 120 miles in 2.5 hours. What is its average speed?", opts: ["42 mph", "46 mph", "48 mph", "50 mph"], ans: 2 },
    { q: "What is 7/12 + 5/8?", opts: ["12/20", "29/24", "1/2", "3/4"], ans: 1 },
    { q: "What is the next prime after 13?", opts: ["14", "15", "17", "19"], ans: 2 },
    { q: "Evaluate: 3 + 4 × 2 - 1", opts: ["13", "12", "10", "9"], ans: 2 },
    { q: "What is 10% of 10% of 1000?", opts: ["1", "10", "100", "0.1"], ans: 1 },
    { q: "Simplify: √(50)", opts: ["5√2", "25√2", "10√5", "5√10"], ans: 0 },
    { q: "What is (-3)² - (-3)?", opts: ["6", "9", "12", "15"], ans: 2 },
    { q: "What is the reciprocal of 3/7?", opts: ["3/7", "-3/7", "7/3", "-7/3"], ans: 2 },
    { q: "What is 1001 × 11?", opts: ["10011", "11011", "11111", "10111"], ans: 1 },
    { q: "A bag has 3 red, 5 blue, 2 green balls. Probability of picking blue?", opts: ["1/2", "5/9", "5/10", "1/3"], ans: 2 },
  ],

  1: [ // EARLY ALGEBRA
    { q: "Solve: 2x + 5 = 13", opts: ["x = 3", "x = 4", "x = 9", "x = 18"], ans: 1 },
    { q: "Solve: 3x - 7 = 14", opts: ["x = 3", "x = 5", "x = 7", "x = 9"], ans: 2 },
    { q: "Simplify: 3x + 2x - x", opts: ["4x", "5x", "6x - x", "3x"], ans: 0 },
    { q: "What is the slope of y = 3x - 5?", opts: ["-5", "3", "-3", "5"], ans: 1 },
    { q: "Solve: x/4 = 7", opts: ["x = 3", "x = 11", "x = 28", "x = 1.75"], ans: 2 },
    { q: "Expand: 3(x + 4)", opts: ["3x + 4", "3x + 7", "3x + 12", "x + 12"], ans: 2 },
    { q: "Solve: 5x + 2 = 3x + 10", opts: ["x = 2", "x = 4", "x = 6", "x = 8"], ans: 1 },
    { q: "What is the y-intercept of y = 2x + 7?", opts: ["2", "-2", "7", "-7"], ans: 2 },
    { q: "Simplify: 4(2x - 3) + 5", opts: ["8x - 7", "8x - 17", "8x + 7", "6x - 7"], ans: 0 },
    { q: "Solve: -3x = 18", opts: ["x = -6", "x = 6", "x = -54", "x = 15"], ans: 0 },
    { q: "Factor: x² + 5x + 6", opts: ["(x+2)(x+3)", "(x+1)(x+6)", "(x+3)(x+3)", "(x-2)(x-3)"], ans: 0 },
    { q: "Solve the system: x + y = 5, x - y = 1", opts: ["x=2,y=3", "x=3,y=2", "x=4,y=1", "x=1,y=4"], ans: 1 },
    { q: "What is the slope of a horizontal line?", opts: ["1", "-1", "0", "undefined"], ans: 2 },
    { q: "Simplify: (x³)(x⁴)", opts: ["x⁷", "x¹²", "2x⁷", "x^34"], ans: 0 },
    { q: "Solve: |x| = 9", opts: ["x = 9", "x = -9", "x = 9 or x = -9", "no solution"], ans: 2 },
    { q: "What is the slope between (2,3) and (6,11)?", opts: ["1", "2", "3", "4"], ans: 1 },
    { q: "Solve: 2(x-3) = x + 5", opts: ["x = 8", "x = 11", "x = 1", "x = -1"], ans: 1 },
    { q: "Simplify: (2x²)³", opts: ["6x⁵", "8x⁶", "6x⁶", "8x⁵"], ans: 1 },
    { q: "Factor: x² - 9", opts: ["(x-3)²", "(x+3)(x-3)", "(x-9)(x+1)", "(x+9)(x-1)"], ans: 1 },
    { q: "Solve: x² = 25", opts: ["x = 5", "x = -5", "x = ±5", "x = ±25"], ans: 2 },
    { q: "What is the equation of a line with slope 2 through (0,3)?", opts: ["y = 3x + 2", "y = 2x + 3", "y = 2x - 3", "y = 3x - 2"], ans: 1 },
    { q: "Solve: 3x/5 = 9", opts: ["x = 3", "x = 9", "x = 15", "x = 27"], ans: 2 },
    { q: "Simplify: (3x + 2)(x - 4)", opts: ["3x² - 10x - 8", "3x² - 12x - 8", "3x² + 10x - 8", "3x² - 10x + 8"], ans: 0 },
    { q: "Solve: 4 - 2x > 10", opts: ["x > -3", "x < -3", "x > 3", "x < 3"], ans: 1 },
    { q: "What is f(3) if f(x) = 2x² - x + 1?", opts: ["14", "16", "18", "20"], ans: 1 },
    { q: "Solve: x² - 5x + 6 = 0", opts: ["x=1,x=6", "x=2,x=3", "x=-2,x=-3", "x=2,x=-3"], ans: 1 },
    { q: "Simplify: (x⁴)/(x²)", opts: ["x⁶", "x²", "x⁸", "1"], ans: 1 },
    { q: "What is the domain of f(x) = 1/x?", opts: ["all reals", "x ≠ 0", "x > 0", "x ≥ 0"], ans: 1 },
    { q: "Solve: √x = 7", opts: ["x = 3.5", "x = 14", "x = 49", "x = 7"], ans: 2 },
    { q: "Write in slope-intercept form: 2x - y = 4", opts: ["y = 2x - 4", "y = -2x + 4", "y = 2x + 4", "y = x - 4"], ans: 0 },
    { q: "Factor completely: 2x² - 8", opts: ["2(x²-4)", "2(x-2)(x+2)", "(2x-4)(x+2)", "2(x-4)"], ans: 1 },
    { q: "Solve: (x+2)² = 16", opts: ["x=2 or x=-6", "x=2 or x=6", "x=14 or x=-18", "x=4 or x=-4"], ans: 0 },
    { q: "If f(x) = 3x+1 and g(x) = x², what is f(g(2))?", opts: ["9", "13", "25", "49"], ans: 1 },
    { q: "Solve: |2x - 3| = 7", opts: ["x=5 or x=-2", "x=2 or x=-5", "x=5 only", "x=-2 only"], ans: 0 },
    { q: "What are the x-intercepts of y = x² - 4x + 3?", opts: ["x=1,x=3", "x=-1,x=-3", "x=0,x=4", "x=2,x=2"], ans: 0 },
    { q: "Simplify: (x²y³)/(xy)", opts: ["xy²", "x²y²", "xy³", "x³y⁴"], ans: 0 },
    { q: "Solve: log₂(x) = 3", opts: ["x = 6", "x = 8", "x = 9", "x = 2/3"], ans: 1 },
    { q: "What is the vertex of y = (x-3)² + 2?", opts: ["(3,2)", "(-3,2)", "(3,-2)", "(-3,-2)"], ans: 0 },
    { q: "Solve: 2x² - 3x - 2 = 0", opts: ["x=2,x=-1/2", "x=-2,x=1/2", "x=1,x=-2", "x=2,x=1/2"], ans: 0 },
    { q: "What is the inverse of f(x) = 2x + 6?", opts: ["f⁻¹(x)=(x-6)/2", "f⁻¹(x)=(x+6)/2", "f⁻¹(x)=2x-6", "f⁻¹(x)=x/2+6"], ans: 0 },
    { q: "Simplify: (2x-3)² ", opts: ["4x²-9", "4x²-12x+9", "4x²+12x+9", "2x²-6x+9"], ans: 1 },
    { q: "Solve the system: 2x+3y=12, x-y=1", opts: ["x=3,y=2", "x=2,y=3", "x=4,y=3", "x=3,y=3"], ans: 0 },
    { q: "What is the range of f(x) = x²?", opts: ["all reals", "x≥0", "y≥0", "y>0"], ans: 2 },
    { q: "Factor: 6x² + 11x + 3", opts: ["(2x+3)(3x+1)", "(6x+1)(x+3)", "(3x+3)(2x+1)", "(2x+1)(3x+3)"], ans: 0 },
    { q: "Solve: 3^x = 81", opts: ["x=3", "x=4", "x=27", "x=9"], ans: 1 },
    { q: "What transformation is y = f(x) + 3?", opts: ["shift right 3", "shift left 3", "shift up 3", "shift down 3"], ans: 2 },
    { q: "Simplify: (x-2)/(x²-4)", opts: ["1/(x+2)", "1/(x-2)", "(x-2)/(x+2)", "1/(x²-4)"], ans: 0 },
    { q: "What is the discriminant of x²-4x+5?", opts: ["-4", "4", "36", "-36"], ans: 0 },
    { q: "Solve: e^x = 1", opts: ["x=0", "x=1", "x=e", "x=-1"], ans: 0 },
    { q: "What is the sum of the roots of x²-7x+10=0?", opts: ["7", "10", "-7", "-10"], ans: 0 },
  ],

  2: [ // ADVANCED ALGEBRA
    { q: "Simplify: (x²-9)/(x+3)", opts: ["x-3", "x+3", "(x-3)/(x+3)", "x²-3"], ans: 0 },
    { q: "What is the sum of an arithmetic series with a₁=2, d=3, n=10?", opts: ["155", "160", "165", "170"], ans: 0 },
    { q: "Solve: log(x) + log(x-3) = 1 (base 10)", opts: ["x=5", "x=2", "x=-2", "x=10"], ans: 0 },
    { q: "What is the 8th term of 3, 6, 12, 24...?", opts: ["192", "384", "256", "768"], ans: 1 },
    { q: "Simplify: (3+2i)(1-i)", opts: ["5-i", "3-2i", "1+2i", "5+i"], ans: 0 },
    { q: "What are the asymptotes of y = 1/(x-2)?", opts: ["x=2, y=1", "x=2, y=0", "x=-2, y=0", "x=0, y=2"], ans: 1 },
    { q: "Solve: 2^(x+1) = 32", opts: ["x=3", "x=4", "x=5", "x=6"], ans: 1 },
    { q: "What is |3+4i|?", opts: ["3", "4", "5", "7"], ans: 2 },
    { q: "Find the partial fraction: (x+1)/((x)(x+2))", opts: ["1/2·1/x - 1/2·1/(x+2)", "1/(2x) + 1/(2(x+2))", "1/x - 1/(x+2)", "1/(x+2) - 1/x"], ans: 1 },
    { q: "Solve: x⁴ - 5x² + 4 = 0", opts: ["x=±1,±4", "x=±1,±2", "x=1,2", "x=±2,±4"], ans: 1 },
    { q: "What is the binomial expansion of (x+y)³?", opts: ["x³+y³", "x³+3x²y+3xy²+y³", "x³+3xy+y³", "3x²+3y²"], ans: 1 },
    { q: "How many ways can 5 books be arranged on a shelf?", opts: ["25", "60", "100", "120"], ans: 3 },
    { q: "What is ⁸C₃?", opts: ["24", "56", "112", "336"], ans: 1 },
    { q: "Solve: ln(x) = 3", opts: ["x=e³", "x=3e", "x=3", "x=9"], ans: 0 },
    { q: "What is the common ratio of the geometric sequence 5, 15, 45...?", opts: ["3", "5", "10", "1/3"], ans: 0 },
    { q: "Simplify: i²⁵", opts: ["1", "-1", "i", "-i"], ans: 2 },
    { q: "What is the sum of the infinite geometric series 1 + 1/2 + 1/4...?", opts: ["1.5", "2", "2.5", "3"], ans: 1 },
    { q: "Solve: x^(2/3) = 4", opts: ["x=6", "x=8", "x=12", "x=64"], ans: 1 },
    { q: "What is the remainder when x³-2x+5 is divided by (x-1)?", opts: ["2", "3", "4", "5"], ans: 2 },
    { q: "What is the inverse of f(x) = (x+1)/(x-1)?", opts: ["f⁻¹(x)=(x+1)/(x-1)", "f⁻¹(x)=(x-1)/(x+1)", "(1+x)/(x-1)", "(x-1)/(1-x)"], ans: 0 },
    { q: "How many roots does x⁵-1=0 have in complex numbers?", opts: ["1", "2", "3", "5"], ans: 3 },
    { q: "Simplify: log₃(81) - log₃(9)", opts: ["1", "2", "3", "4"], ans: 1 },
    { q: "What is the period of f(x) = sin(2x)?", opts: ["π/2", "π", "2π", "4π"], ans: 1 },
    { q: "Expand: (2x - 3)⁴ — what is the x² coefficient?", opts: ["54", "108", "216", "36"], ans: 1 },
    { q: "Solve: |x² - 5| = 4", opts: ["x=±1,±3", "x=±3 only", "x=±1 only", "x=1,3"], ans: 0 },
    { q: "Find all real zeros of x³ - 6x² + 11x - 6", opts: ["1,2,3", "1,2,6", "2,3,4", "-1,-2,-3"], ans: 0 },
    { q: "What is the amplitude of y = -3sin(x)?", opts: ["-3", "3", "π", "2π"], ans: 1 },
    { q: "Evaluate: log₄(1/16)", opts: ["-4", "-2", "2", "4"], ans: 1 },
    { q: "Simplify: (2+3i)/(1-i)", opts: ["-1/2+5i/2", "5/2+i/2", "-1+5i/2", "5+i"], ans: 0 },
    { q: "What is the 5th term in the binomial expansion of (x+2)⁶?", opts: ["60x²", "120x²", "240x", "60x"], ans: 1 },
    { q: "Solve: 2log(x) = log(4x)", opts: ["x=0", "x=4", "x=2", "x=16"], ans: 1 },
    { q: "What is the vertex form of y=x²+6x+5?", opts: ["(x+3)²-4", "(x-3)²-4", "(x+3)²+4", "(x+6)²-4"], ans: 0 },
    { q: "How many ways can you choose 2 from 8?", opts: ["16", "28", "56", "112"], ans: 1 },
    { q: "What is the horizontal asymptote of f(x)=(3x²+1)/(x²-4)?", opts: ["y=0", "y=1", "y=3", "y=-3"], ans: 2 },
    { q: "Solve: 4^x = 8", opts: ["x=1/2", "x=3/2", "x=2", "x=3"], ans: 1 },
    { q: "Simplify: √(-36)", opts: ["6", "-6", "6i", "-6i"], ans: 2 },
    { q: "What is the sum of a geometric series with a₁=3, r=2, n=5?", opts: ["93", "96", "99", "63"], ans: 0 },
    { q: "Find: (x³-8)/(x-2)", opts: ["x²+4", "x²+2x+4", "x²-2x+4", "x²+2x-4"], ans: 1 },
    { q: "Solve: x = √(x+6)", opts: ["x=2", "x=3", "x=2 or x=3", "x=-2 or x=3"], ans: 1 },
    { q: "What is the product of roots of 2x²-5x+3=0?", opts: ["5/2", "-5/2", "3/2", "-3/2"], ans: 2 },
    { q: "Simplify: (a²b³)^(1/3) · a^(1/3)", opts: ["a·b", "a^(7/3)·b", "ab", "a^(7/3)·b"], ans: 1 },
    { q: "What is the phase shift of y=sin(x-π/3)?", opts: ["π/3 left", "π/3 right", "π/6 right", "π/6 left"], ans: 1 },
    { q: "Solve: 9^x - 4·3^x + 3 = 0", opts: ["x=0,x=1", "x=1,x=2", "x=0,x=2", "x=-1,x=1"], ans: 0 },
    { q: "What is the range of y = 2sin(x) + 1?", opts: ["[-1,3]", "[-2,2]", "[0,2]", "[-1,1]"], ans: 0 },
    { q: "Find the oblique asymptote of (x²+x+1)/(x-1)", opts: ["y=x", "y=x+2", "y=x+1", "y=x-1"], ans: 1 },
    { q: "Expand using Pascal's triangle: (a+b)⁵ — coefficient of a²b³?", opts: ["5", "10", "15", "20"], ans: 1 },
    { q: "What is log₅(125√5)?", opts: ["3", "3.5", "4", "7/2"], ans: 1 },
    { q: "Solve: x^4 - 16 = 0 (real solutions only)", opts: ["x=2", "x=±2", "x=±4", "x=2,x=-2,x=2i"], ans: 1 },
    { q: "What is the period of y=tan(3x)?", opts: ["π/3", "π", "3π", "2π/3"], ans: 0 },
    { q: "Simplify: ⁿCₙ for any n", opts: ["0", "1", "n", "n!"], ans: 1 },
  ],

  3: [ // GEOMETRY
    { q: "What is the area of a circle with radius 5?", opts: ["10π", "20π", "25π", "50π"], ans: 2 },
    { q: "What is the sum of interior angles of a pentagon?", opts: ["360°", "450°", "540°", "720°"], ans: 2 },
    { q: "Two angles are supplementary. One is 65°. What is the other?", opts: ["25°", "35°", "115°", "125°"], ans: 2 },
    { q: "What is the volume of a cube with side 4?", opts: ["16", "48", "64", "96"], ans: 2 },
    { q: "A right triangle has legs 6 and 8. What is the hypotenuse?", opts: ["10", "12", "14", "√100"], ans: 0 },
    { q: "What is the surface area of a sphere with radius 3?", opts: ["12π", "18π", "36π", "54π"], ans: 2 },
    { q: "Two parallel lines are cut by a transversal. Alternate interior angles are:", opts: ["supplementary", "complementary", "equal", "add to 180°"], ans: 2 },
    { q: "What is the perimeter of a regular hexagon with side 7?", opts: ["35", "42", "49", "56"], ans: 1 },
    { q: "What is the area of a triangle with base 12 and height 9?", opts: ["54", "108", "72", "36"], ans: 0 },
    { q: "What is the diagonal of a rectangle with sides 5 and 12?", opts: ["13", "15", "17", "169"], ans: 0 },
    { q: "A cylinder has radius 3 and height 7. What is its volume?", opts: ["21π", "42π", "63π", "126π"], ans: 2 },
    { q: "What is the measure of each interior angle of a regular octagon?", opts: ["120°", "135°", "140°", "150°"], ans: 1 },
    { q: "Two triangles are similar with ratio 2:3. If the smaller has area 16, what is the larger area?", opts: ["24", "32", "36", "54"], ans: 2 },
    { q: "What is the arc length of a 90° sector with radius 8?", opts: ["2π", "4π", "8π", "16π"], ans: 1 },
    { q: "A cone has radius 3 and height 4. What is its slant height?", opts: ["4", "5", "6", "7"], ans: 1 },
    { q: "What is the distance between (-1,2) and (3,-1)?", opts: ["3", "4", "5", "√7"], ans: 2 },
    { q: "A parallelogram has base 8 and height 6. What is its area?", opts: ["24", "36", "48", "56"], ans: 2 },
    { q: "What is the midpoint of (2,4) and (8,10)?", opts: ["(4,6)", "(5,7)", "(6,8)", "(3,5)"], ans: 1 },
    { q: "The volume of a sphere with radius r is:", opts: ["4πr²", "(4/3)πr³", "(2/3)πr³", "πr³"], ans: 1 },
    { q: "Two angles of a triangle are 45° and 75°. What is the third?", opts: ["45°", "60°", "70°", "80°"], ans: 1 },
    { q: "What is the area of a sector with radius 6 and central angle 60°?", opts: ["3π", "6π", "9π", "12π"], ans: 1 },
    { q: "In a 30-60-90 triangle with short leg 4, what is the hypotenuse?", opts: ["4", "4√3", "8", "8√3"], ans: 2 },
    { q: "What is the circumference of a circle with diameter 14?", opts: ["7π", "14π", "28π", "196π"], ans: 1 },
    { q: "A rhombus has diagonals of 10 and 6. What is its area?", opts: ["16", "30", "36", "60"], ans: 1 },
    { q: "What is the equation of a circle with center (2,-1) and radius 4?", opts: ["(x-2)²+(y+1)²=4", "(x-2)²+(y+1)²=16", "(x+2)²+(y-1)²=16", "(x-2)²+(y-1)²=16"], ans: 1 },
    { q: "The diagonals of a rectangle are always:", opts: ["perpendicular", "equal", "bisecting at right angles", "unequal"], ans: 1 },
    { q: "What is the volume of a pyramid with square base 6×6 and height 9?", opts: ["54", "108", "162", "324"], ans: 1 },
    { q: "In a 45-45-90 triangle, the hypotenuse is 10. What are the legs?", opts: ["5", "5√2", "10/√2", "5√3"], ans: 1 },
    { q: "What is the sum of exterior angles of any convex polygon?", opts: ["180°", "270°", "360°", "depends on n"], ans: 2 },
    { q: "A trapezoid has parallel sides 5 and 9 and height 4. What is its area?", opts: ["28", "32", "36", "40"], ans: 0 },
    { q: "What is cos(60°)?", opts: ["√3/2", "1/2", "√2/2", "1"], ans: 1 },
    { q: "What is sin(45°)?", opts: ["1/2", "√3/2", "√2/2", "1"], ans: 2 },
    { q: "In a circle, a chord is 8 and the radius is 5. How far is the chord from the center?", opts: ["2", "3", "4", "5"], ans: 1 },
    { q: "What is tan(30°)?", opts: ["1/√3", "√3", "√3/2", "1/2"], ans: 0 },
    { q: "A regular polygon has interior angles of 150°. How many sides?", opts: ["10", "12", "14", "16"], ans: 1 },
    { q: "Two triangles have sides 3,4,5 and 6,8,10. Are they similar?", opts: ["No", "Yes, ratio 1:2", "Yes, ratio 2:3", "Cannot tell"], ans: 1 },
    { q: "What is the lateral surface area of a cone with r=3, l=5?", opts: ["5π", "10π", "15π", "45π"], ans: 2 },
    { q: "What transformation maps (x,y) to (-x,y)?", opts: ["rotation 90°", "reflection over y-axis", "reflection over x-axis", "translation"], ans: 1 },
    { q: "A square is inscribed in a circle of radius 5. What is the square's area?", opts: ["25", "50", "100", "25√2"], ans: 1 },
    { q: "What is the length of the altitude from the right angle in a right triangle with legs 3 and 4?", opts: ["2", "12/5", "5/2", "7/5"], ans: 1 },
    { q: "What is the slope of a line perpendicular to y = 3x + 1?", opts: ["3", "-3", "1/3", "-1/3"], ans: 3 },
    { q: "In a circle, an inscribed angle is half the:", opts: ["radius", "chord", "central angle", "arc length"], ans: 2 },
    { q: "What is the area of an equilateral triangle with side 6?", opts: ["9√3", "12√3", "18√3", "6√3"], ans: 0 },
    { q: "A dilation with factor 3 changes area by a factor of:", opts: ["3", "6", "9", "27"], ans: 2 },
    { q: "What is the angle in a semicircle (Thales' theorem)?", opts: ["45°", "60°", "90°", "180°"], ans: 2 },
    { q: "What is the surface area of a cylinder with r=2, h=5?", opts: ["14π", "18π", "20π", "28π"], ans: 3 },
    { q: "What is the geometric mean of 4 and 16?", opts: ["8", "10", "6", "12"], ans: 0 },
    { q: "In triangle ABC, if AB=5, BC=7, AC=8, find cos(B) using the law of cosines.", opts: ["1/7", "5/7", "11/14", "1/2"], ans: 2 },
    { q: "What is the area of a regular hexagon with side 4?", opts: ["24√3", "12√3", "48√3", "6√3"], ans: 0 },
    { q: "A circle has equation x²+y²-4x+6y=3. What is the radius?", opts: ["3", "4", "√16", "4"], ans: 3 },
  ],

  4: [ // PRE-CALCULUS
    { q: "What is sin²(x) + cos²(x)?", opts: ["0", "1", "2", "sin(2x)"], ans: 1 },
    { q: "Evaluate: lim(x→2) (x²-4)/(x-2)", opts: ["0", "2", "4", "undefined"], ans: 2 },
    { q: "What is the exact value of sin(π/6)?", opts: ["√3/2", "1/2", "√2/2", "1"], ans: 1 },
    { q: "What is the period of y = cos(x/2)?", opts: ["π", "2π", "4π", "π/2"], ans: 2 },
    { q: "Simplify: (1-cos²x)/sinx", opts: ["sinx", "cosx", "tanx", "1"], ans: 0 },
    { q: "What is the exact value of tan(π/4)?", opts: ["0", "1/√2", "1", "√3"], ans: 2 },
    { q: "What is lim(x→∞) (3x²+1)/(x²+2)?", opts: ["0", "1", "3", "∞"], ans: 2 },
    { q: "Convert 150° to radians.", opts: ["5π/6", "2π/3", "3π/4", "π/6"], ans: 0 },
    { q: "What is the double angle formula for sin(2x)?", opts: ["2sin(x)", "2sin(x)cos(x)", "cos²(x)-sin²(x)", "1-2sin²(x)"], ans: 1 },
    { q: "Find the exact value of cos(π/3).", opts: ["1/2", "√3/2", "√2/2", "√3"], ans: 0 },
    { q: "What is the inverse function of sin(x)?", opts: ["cos(x)", "tan(x)", "arcsin(x)", "csc(x)"], ans: 2 },
    { q: "What is lim(x→0) sin(x)/x?", opts: ["0", "1", "∞", "undefined"], ans: 1 },
    { q: "Solve: 2sin(x) = 1 for x ∈ [0,2π]", opts: ["π/6 only", "π/6, 5π/6", "π/3, 2π/3", "π/4, 3π/4"], ans: 1 },
    { q: "What is the dot product of (2,3) and (4,-1)?", opts: ["5", "6", "7", "8"], ans: 0 },
    { q: "What is the polar form of the point (0, -3)?", opts: ["(3, π/2)", "(3, 3π/2)", "(-3, π)", "(3, π)"], ans: 1 },
    { q: "Simplify: sec²(x) - 1", opts: ["sin²(x)", "cos²(x)", "tan²(x)", "cot²(x)"], ans: 2 },
    { q: "What is lim(x→0) (1+x)^(1/x)?", opts: ["0", "1", "e", "∞"], ans: 2 },
    { q: "What is cos(π)?", opts: ["0", "1", "-1", "undefined"], ans: 2 },
    { q: "Convert 5π/4 to degrees.", opts: ["200°", "210°", "225°", "240°"], ans: 2 },
    { q: "What is the sum-to-product formula for cos(A)+cos(B)?", opts: ["2cos((A+B)/2)sin((A-B)/2)", "2cos((A+B)/2)cos((A-B)/2)", "2sin((A+B)/2)cos((A-B)/2)", "2sin((A+B)/2)sin((A-B)/2)"], ans: 1 },
    { q: "What is the magnitude of vector (3, -4, 0)?", opts: ["3", "4", "5", "7"], ans: 2 },
    { q: "Solve 2cos²(x) - cos(x) - 1 = 0 for x ∈ [0,2π]", opts: ["π/3,5π/3,π", "π/3,π/6", "π/2,π", "π/3,5π/3"], ans: 0 },
    { q: "What is the cross product of i and j?", opts: ["i", "j", "k", "-k"], ans: 2 },
    { q: "Find: lim(x→3) (x²-9)/(x-3)", opts: ["3", "6", "9", "0"], ans: 1 },
    { q: "What is the rectangular form of 2(cos(π/3)+i·sin(π/3))?", opts: ["1+i√3", "√3+i", "2+2i", "1+√3i"], ans: 0 },
    { q: "What is the identity for cos(A-B)?", opts: ["cosA cosB + sinA sinB", "cosA cosB - sinA sinB", "sinA cosB - cosA sinB", "sinA cosB + cosA sinB"], ans: 0 },
    { q: "Find the angle between vectors (1,0) and (1,1).", opts: ["30°", "45°", "60°", "90°"], ans: 1 },
    { q: "What is the range of arcsin(x)?", opts: ["[0,π]", "[-π/2,π/2]", "(-π/2,π/2)", "(-π,π)"], ans: 1 },
    { q: "Simplify: sin(π - x)", opts: ["sin(x)", "-sin(x)", "cos(x)", "-cos(x)"], ans: 0 },
    { q: "What is the parametric form of a circle of radius r?", opts: ["x=rsinθ,y=rcosθ", "x=rcosθ,y=rsinθ", "x=r,y=rθ", "x=cosθ,y=sinθ"], ans: 1 },
    { q: "Evaluate: lim(x→∞) x·sin(1/x)", opts: ["0", "1", "∞", "-1"], ans: 1 },
    { q: "What is cot(π/4)?", opts: ["0", "1", "√3", "1/√3"], ans: 1 },
    { q: "Solve: tan(x) = √3 for x ∈ [0, 2π]", opts: ["π/3 only", "π/3, 4π/3", "π/6, 7π/6", "π/4, 5π/4"], ans: 1 },
    { q: "What is the projection of vector a onto vector b?", opts: ["(a·b)/|b|", "(a·b)/|b|² · b", "|a|cos(θ)", "a×b"], ans: 1 },
    { q: "What does it mean for a function to be even?", opts: ["f(-x)=-f(x)", "f(x)=f(-x)", "f(x+T)=f(x)", "f(x)>0"], ans: 1 },
    { q: "What is the Pythagorean identity involving tan?", opts: ["tan²x+1=sec²x", "tan²x-1=sec²x", "1+tan²x=csc²x", "tan²x=sin²x/cos²x+1"], ans: 0 },
    { q: "What is the argument of the complex number -1 + i?", opts: ["π/4", "3π/4", "-π/4", "5π/4"], ans: 1 },
    { q: "What is the Law of Sines?", opts: ["a/sinA=b/sinB=c/sinC", "a²=b²+c²-2bc cosA", "sinA/a=sinB/b", "a/b=sinA/sinB"], ans: 0 },
    { q: "Evaluate: sin(5π/6)", opts: ["1/2", "√3/2", "-1/2", "-√3/2"], ans: 0 },
    { q: "Find the sum: Σ(k=1 to 5) 2k", opts: ["20", "25", "30", "35"], ans: 2 },
    { q: "What is the period of y = 3tan(2x - π)?", opts: ["π/4", "π/2", "π", "2π"], ans: 1 },
    { q: "What is DeMoivre's theorem?", opts: ["(r·cisθ)ⁿ=rⁿ·cis(nθ)", "(a+bi)ⁿ=aⁿ+bⁿ", "r^n = (a²+b²)^n", "nθ = arg(zⁿ)"], ans: 0 },
    { q: "Evaluate: cos(7π/6)", opts: ["1/2", "-1/2", "√3/2", "-√3/2"], ans: 3 },
    { q: "What is the horizontal asymptote of f(x) = (2x³)/(x³+1)?", opts: ["y=0", "y=1", "y=2", "y=3"], ans: 2 },
    { q: "Find: lim(x→0⁺) ln(x)", opts: ["0", "1", "-∞", "∞"], ans: 2 },
    { q: "What is the half-angle formula for sin(x/2)?", opts: ["±√((1-cosx)/2)", "±√((1+cosx)/2)", "sinx/2", "1/2·sinx"], ans: 0 },
    { q: "Simplify: sin(x+π)", opts: ["sin(x)", "-sin(x)", "cos(x)", "-cos(x)"], ans: 1 },
    { q: "What is the eccentricity of a circle?", opts: ["0", "1", "between 0 and 1", ">1"], ans: 0 },
    { q: "Solve: e^(2x) - 3e^x + 2 = 0", opts: ["x=0 only", "x=0, x=ln2", "x=ln2 only", "x=1,x=2"], ans: 1 },
    { q: "What is the formula for arc length in polar coordinates?", opts: ["∫√(r²+(dr/dθ)²)dθ", "∫r dθ", "∫r²dθ/2", "∫√(1+r²)dθ"], ans: 0 },
  ],

  5: [ // CALCULUS I
    { q: "What is d/dx[x³]?", opts: ["x²", "3x²", "x⁴/4", "3x"], ans: 1 },
    { q: "What is d/dx[sin(x)]?", opts: ["cos(x)", "-cos(x)", "sin(x)", "-sin(x)"], ans: 0 },
    { q: "What is ∫x dx?", opts: ["x²", "x²/2 + C", "2x + C", "x + C"], ans: 1 },
    { q: "What is d/dx[e^x]?", opts: ["e^x", "xe^(x-1)", "e^(x-1)", "1"], ans: 0 },
    { q: "What is ∫cos(x) dx?", opts: ["sin(x)+C", "-sin(x)+C", "cos(x)+C", "-cos(x)+C"], ans: 0 },
    { q: "What is the derivative of ln(x)?", opts: ["1/x", "ln(x)/x", "x·ln(x)", "e^x"], ans: 0 },
    { q: "Find d/dx[x² sin(x)] using product rule.", opts: ["2x cos(x)", "x² cos(x) + 2x sin(x)", "2x sin(x)", "x² cos(x)"], ans: 1 },
    { q: "What is ∫₀¹ x² dx?", opts: ["1/4", "1/3", "1/2", "1"], ans: 1 },
    { q: "What is the chain rule for d/dx[f(g(x))]?", opts: ["f'(x)g'(x)", "f'(g(x))·g'(x)", "f(g'(x))", "f'(g(x))"], ans: 1 },
    { q: "At what x is f(x) = x³ - 3x concave up?", opts: ["x < 0", "x > 0", "x < 1", "all x"], ans: 1 },
    { q: "What is d/dx[tan(x)]?", opts: ["sec(x)", "sec²(x)", "-csc²(x)", "cos²(x)"], ans: 1 },
    { q: "What is ∫ e^x dx?", opts: ["xe^x+C", "e^x+C", "e^(x+1)+C", "e^x·x+C"], ans: 1 },
    { q: "What is the second derivative of f(x) = x⁴?", opts: ["4x³", "12x²", "24x", "4x"], ans: 1 },
    { q: "What does f'(x) = 0 indicate?", opts: ["inflection point", "local max or min", "discontinuity", "asymptote"], ans: 1 },
    { q: "What is ∫ 1/x dx?", opts: ["x⁻¹+C", "ln|x|+C", "-1/x²+C", "1/x+C"], ans: 1 },
    { q: "Find the derivative of f(x) = (x²+1)⁵.", opts: ["5(x²+1)⁴", "10x(x²+1)⁴", "5x(x²+1)⁴", "2x(x²+1)⁴"], ans: 1 },
    { q: "What is the area under y=x from x=0 to x=4?", opts: ["4", "8", "12", "16"], ans: 1 },
    { q: "What is lim(x→0) (e^x - 1)/x?", opts: ["0", "1", "e", "∞"], ans: 1 },
    { q: "What is d/dx[arctan(x)]?", opts: ["1/x", "1/(1+x²)", "-1/(1+x²)", "1/√(1-x²)"], ans: 1 },
    { q: "What is ∫ sin(x) dx?", opts: ["cos(x)+C", "-cos(x)+C", "sin(x)+C", "-sin(x)+C"], ans: 1 },
    { q: "Use L'Hôpital's rule: lim(x→0) sin(x)/x", opts: ["0", "1", "∞", "sin(0)"], ans: 1 },
    { q: "What is the critical point of f(x) = x² - 4x + 3?", opts: ["x=1", "x=2", "x=3", "x=4"], ans: 1 },
    { q: "What is d/dx[x^n] (power rule)?", opts: ["nx", "nx^(n-1)", "x^(n+1)/(n+1)", "n^x"], ans: 1 },
    { q: "Evaluate: ∫₀^π sin(x) dx", opts: ["0", "1", "2", "π"], ans: 2 },
    { q: "What is the Fundamental Theorem of Calculus (Part 1)?", opts: ["d/dx∫ₐˣf(t)dt=f(x)", "∫ₐᵇf(x)dx=F(b)-F(a)", "∫f'(x)dx=f(x)", "all of the above"], ans: 0 },
    { q: "Find d/dx[ln(x²+1)].", opts: ["1/(x²+1)", "2x/(x²+1)", "ln(2x)", "2x·ln(x²+1)"], ans: 1 },
    { q: "What is ∫ 2x/(x²+1) dx?", opts: ["ln(x²+1)+C", "arctan(x)+C", "x²+ln(x)+C", "1/(x²+1)+C"], ans: 0 },
    { q: "Find the inflection point of f(x) = x³ - 6x².", opts: ["x=0", "x=2", "x=4", "x=6"], ans: 1 },
    { q: "What is d/dx[cos²(x)]?", opts: ["-2cos(x)", "-2sin(x)cos(x)", "2cos(x)sin(x)", "2cos(x)"], ans: 1 },
    { q: "What does the Mean Value Theorem guarantee?", opts: ["a root exists", "a point where f'(c)=(f(b)-f(a))/(b-a)", "the function is continuous", "a maximum exists"], ans: 1 },
    { q: "What is ∫ x·e^x dx?", opts: ["x·e^x+C", "(x-1)e^x+C", "e^x(x+1)+C", "x²e^x+C"], ans: 1 },
    { q: "Find: d/dx[x/sin(x)]", opts: ["(sin(x)-x·cos(x))/sin²(x)", "(cos(x)-x)/sin(x)", "1/cos(x)", "cot(x)-xcsc²(x)"], ans: 0 },
    { q: "What is the derivative of arcsin(x)?", opts: ["1/√(1-x²)", "-1/√(1-x²)", "1/(1+x²)", "arccos(x)"], ans: 0 },
    { q: "Evaluate: ∫₁² (1/x) dx", opts: ["0", "ln(2)", "1", "2"], ans: 1 },
    { q: "What is the absolute maximum of f(x) = -x²+4x on [0,5]?", opts: ["3", "4", "5", "0"], ans: 1 },
    { q: "What is d²/dx²[sin(x)]?", opts: ["cos(x)", "-cos(x)", "sin(x)", "-sin(x)"], ans: 3 },
    { q: "What is implicit differentiation used for?", opts: ["functions not solved for y", "exponential functions", "trigonometric identities", "series"], ans: 0 },
    { q: "Find: ∫ sec²(x) dx", opts: ["sec(x)tan(x)+C", "tan(x)+C", "2sec(x)+C", "cot(x)+C"], ans: 1 },
    { q: "What is d/dx[a^x] where a is a constant?", opts: ["xa^(x-1)", "a^x", "a^x · ln(a)", "a^x / ln(a)"], ans: 2 },
    { q: "What is the average value of f(x)=x² on [0,3]?", opts: ["2", "3", "4", "9"], ans: 1 },
    { q: "Use substitution: ∫ 2x·cos(x²) dx", opts: ["sin(x²)+C", "2sin(x)+C", "cos(x²)+C", "-sin(x²)+C"], ans: 0 },
    { q: "What is Newton's method for finding roots?", opts: ["xₙ₊₁ = xₙ - f(xₙ)/f'(xₙ)", "xₙ₊₁ = xₙ - f'(xₙ)/f(xₙ)", "xₙ₊₁ = f(xₙ)/f'(xₙ)", "xₙ₊₁ = xₙ + f(xₙ)"], ans: 0 },
    { q: "What is ∫₋₁¹ x³ dx?", opts: ["-1/4", "0", "1/4", "1/2"], ans: 1 },
    { q: "Find the local minimum of f(x) = x³ - 3x.", opts: ["x=-1", "x=0", "x=1", "x=2"], ans: 2 },
    { q: "What is d/dx[√(x²+4)]?", opts: ["x/√(x²+4)", "1/√(x²+4)", "2x/√(x²+4)", "x/(x²+4)"], ans: 0 },
    { q: "What does ∫ₐᵇ f(x)dx represent geometrically?", opts: ["slope", "signed area under curve", "length of curve", "volume"], ans: 1 },
    { q: "What is the linearization of f(x) = √x at x = 4?", opts: ["L(x) = 2 + (x-4)/4", "L(x) = 2 + x/4", "L(x) = x/4", "L(x) = 4 + (x-4)/4"], ans: 0 },
    { q: "What is Rolle's Theorem?", opts: ["if f continuous on [a,b] and f(a)=f(b), then f'(c)=0 for some c", "if f'(c)=0 then c is a max", "every continuous function has a zero", "f(a)=f(b) implies f is constant"], ans: 0 },
    { q: "Evaluate: d/dx[∫₀^(x²) sin(t) dt]", opts: ["sin(x²)", "2x·sin(x²)", "cos(x²)", "2x·cos(x²)"], ans: 1 },
    { q: "What is the integral ∫ tan(x) dx?", opts: ["sec²(x)+C", "ln|cos(x)|+C", "-ln|cos(x)|+C", "ln|sin(x)|+C"], ans: 2 },
  ],

  6: [ // CALCULUS II / ADVANCED
    { q: "What is the integral ∫ x·ln(x) dx?", opts: ["x²ln(x)/2 - x²/4 + C", "x²ln(x)/2 + C", "ln(x)/x + C", "x·ln(x) - x + C"], ans: 0 },
    { q: "What test determines if Σ 1/n² converges?", opts: ["ratio test", "root test", "p-series test", "divergence test"], ans: 2 },
    { q: "What is the Taylor series for e^x?", opts: ["Σ x^n/n!", "Σ x^n", "Σ (-1)^n x^n/n!", "Σ x^n/n"], ans: 0 },
    { q: "What is ∫ x²·e^x dx?", opts: ["e^x(x²-2x+2)+C", "x²e^x+C", "e^x(x²+2x+2)+C", "2xe^x+C"], ans: 0 },
    { q: "Does Σ 1/n converge?", opts: ["yes", "no, it diverges", "depends on starting index", "conditionally converges"], ans: 1 },
    { q: "What is the volume of revolution around x-axis using disk method?", opts: ["π∫[f(x)]²dx", "2π∫x·f(x)dx", "∫[f(x)]²dx", "π∫f(x)dx"], ans: 0 },
    { q: "What is the Maclaurin series for sin(x)?", opts: ["Σ(-1)^n x^(2n)/(2n)!", "Σ(-1)^n x^(2n+1)/(2n+1)!", "Σ x^n/n!", "Σ(-1)^n x^n/n!"], ans: 1 },
    { q: "What is ∫ 1/(x²-1) dx?", opts: ["(1/2)ln|(x-1)/(x+1)|+C", "arctan(x)+C", "ln|x²-1|+C", "1/(2x)+C"], ans: 0 },
    { q: "What is the ratio test condition for convergence?", opts: ["lim|aₙ₊₁/aₙ| < 1", "lim|aₙ₊₁/aₙ| > 1", "lim|aₙ₊₁/aₙ| = 1", "lim aₙ = 0"], ans: 0 },
    { q: "What is ∫₀^∞ e^(-x) dx?", opts: ["0", "1", "e", "∞"], ans: 1 },
    { q: "Find the area between y=x² and y=x.", opts: ["1/3", "1/6", "1/2", "1/4"], ans: 1 },
    { q: "What is the shell method formula for volume?", opts: ["2π∫x·f(x)dx", "π∫[f(x)]²dx", "∫f(x)dx", "π∫[f(x)-g(x)]²dx"], ans: 0 },
    { q: "What is the arc length formula for y=f(x) from a to b?", opts: ["∫√(1+[f'(x)]²)dx", "∫√(1+[f(x)]²)dx", "∫[f'(x)]²dx", "∫f'(x)dx"], ans: 0 },
    { q: "Does Σ (-1)^n/n converge?", opts: ["no", "yes, absolutely", "yes, conditionally", "only if n is even"], ans: 2 },
    { q: "What is the power series for 1/(1-x) for |x|<1?", opts: ["Σ xⁿ", "Σ (-1)^n xⁿ", "Σ xⁿ/n!", "Σ nxⁿ"], ans: 0 },
    { q: "What is ∫ sin²(x) dx?", opts: ["x/2 - sin(2x)/4 + C", "cos²(x)/2 + C", "-cos(2x)/2 + C", "sin(2x)/2 + C"], ans: 0 },
    { q: "What is the integral test for series?", opts: ["if ∫f(x)dx converges, Σf(n) converges", "if f(n) converges, ∫f(x)dx converges", "both diverge or both converge", "a and c"], ans: 2 },
    { q: "Find the radius of convergence of Σ xⁿ/n.", opts: ["0", "1", "e", "∞"], ans: 1 },
    { q: "What is the second derivative test for local max?", opts: ["f'(c)=0 and f''(c)<0", "f'(c)=0 and f''(c)>0", "f''(c)=0", "f'(c)<0"], ans: 0 },
    { q: "Evaluate: ∫ x/(x²+1) dx", opts: ["arctan(x)+C", "(1/2)ln(x²+1)+C", "ln(x²+1)+C", "x²/(2(x²+1))+C"], ans: 1 },
    { q: "What is integration by parts formula?", opts: ["∫u dv = uv - ∫v du", "∫u dv = uv + ∫v du", "∫u v dx = u'v - uv'", "∫f(g(x)) = f(g(x))·g'(x)"], ans: 0 },
    { q: "What is ∫ sec(x) dx?", opts: ["ln|sec(x)+tan(x)|+C", "tan(x)+C", "sec(x)tan(x)+C", "ln|cos(x)|+C"], ans: 0 },
    { q: "Does the alternating series Σ (-1)^n/n² converge absolutely?", opts: ["no", "yes", "conditionally only", "diverges"], ans: 1 },
    { q: "What is the Maclaurin series for cos(x)?", opts: ["Σ(-1)^n x^(2n+1)/(2n+1)!", "Σ(-1)^n x^(2n)/(2n)!", "Σ x^(2n)/(2n)!", "Σ(-1)^n x^n/(2n)!"], ans: 1 },
    { q: "What is the area in polar coordinates for r=f(θ)?", opts: ["∫r dθ", "(1/2)∫r² dθ", "∫r² dθ", "(1/2)∫r dθ"], ans: 1 },
    { q: "Evaluate: ∫₀¹ x·e^x dx", opts: ["1", "e-1", "e", "e+1"], ans: 0 },
    { q: "What is the Lagrange error bound for Taylor polynomials?", opts: ["|Rₙ(x)| ≤ M|x-a|^(n+1)/(n+1)!", "|Rₙ(x)| = f^(n+1)(c)", "∫|f^(n+1)|dx", "M/(n+1)"], ans: 0 },
    { q: "What is ∫ x³·e^(x²) dx?", opts: ["(x²-1)e^(x²)/2+C", "x²e^(x²)/2+C", "e^(x²)(x²-1)+C", "(1/2)(x²-1)e^(x²)+C"], ans: 3 },
    { q: "Find: d/dx[∫_{x}^{x²} sin(t²) dt]", opts: ["2x·sin(x⁴)-sin(x²)", "sin(x⁴)-sin(x²)", "2x·sin(x⁴)", "sin(x²)"], ans: 0 },
    { q: "What does it mean for a series to converge absolutely?", opts: ["Σ|aₙ| converges", "Σaₙ converges", "aₙ→0", "|aₙ|<1"], ans: 0 },
    { q: "What is the Fourier series used for?", opts: ["solving ODEs", "representing periodic functions as trig series", "finding derivatives", "integration by parts"], ans: 1 },
    { q: "Evaluate: ∫₀^(π/2) sin²(x)cos(x) dx", opts: ["1/2", "1/3", "π/4", "2/3"], ans: 1 },
    { q: "What is the comparison test for series?", opts: ["compare with known convergent/divergent series", "compare terms with 0", "compare with geometric series only", "compare with p-series only"], ans: 0 },
    { q: "What is the improper integral ∫₁^∞ 1/x² dx?", opts: ["∞", "0", "1", "2"], ans: 2 },
    { q: "Find the interval of convergence for Σ (x-2)^n/n.", opts: ["[1,3)", "1<x≤3", "1≤x<3", "(1,3]"], ans: 3 },
    { q: "What is ∫ 1/√(1-x²) dx?", opts: ["arcsin(x)+C", "arccos(x)+C", "arctan(x)+C", "-arcsin(x)+C"], ans: 0 },
    { q: "What is the surface area of revolution formula?", opts: ["2π∫y·√(1+y'²)dx", "π∫y²dx", "2π∫y dx", "∫√(1+y'²)dx"], ans: 0 },
    { q: "Evaluate: lim(n→∞) (1 + 1/n)^n", opts: ["1", "2", "e", "∞"], ans: 2 },
    { q: "What test for Σ n·(1/2)^n?", opts: ["p-series", "ratio test", "root test", "integral test"], ans: 1 },
    { q: "What is ∫ cos³(x) dx?", opts: ["sin(x) - sin³(x)/3 + C", "3cos²(x) + C", "sin(x)/3 + C", "cos²(x)·sin(x)/3 + C"], ans: 0 },
    { q: "What is the formula for the centroid x̄ of a region?", opts: ["∫x·f(x)dx / ∫f(x)dx", "∫f(x)dx", "∫x dx / Area", "Area/∫f(x)dx"], ans: 0 },
    { q: "Evaluate: ∫ dx/(x·√(x²-1))", opts: ["arctan(x)+C", "arcsec(x)+C", "arcsin(x)+C", "ln|x|+C"], ans: 1 },
    { q: "What does Σ 1/n^p converge for?", opts: ["p > 0", "p > 1", "p ≥ 1", "p < 1"], ans: 1 },
    { q: "What is the Cauchy-Schwarz inequality for integrals?", opts: ["[∫fg]² ≤ ∫f²·∫g²", "∫fg ≤ ∫f+∫g", "∫|fg| = |∫f·∫g|", "∫fg ≤ max(f)·∫g"], ans: 0 },
    { q: "Find: ∫ x²/(x+1) dx", opts: ["x²/2 - x + ln|x+1| + C", "x²/2 + ln|x+1| + C", "x - ln|x+1| + C", "x³/3/(x+1) + C"], ans: 0 },
    { q: "What is the formula for work done by a variable force F(x)?", opts: ["F·d", "∫F(x)dx", "∫F(x)/x dx", "F(b)-F(a)"], ans: 1 },
    { q: "What is the Squeeze Theorem?", opts: ["if g≤f≤h and lim g=lim h=L, then lim f=L", "if f≤g then lim f ≤ lim g", "squeeze between two values", "if lim f=0 and g bounded, lim fg=0"], ans: 0 },
    { q: "Evaluate: ∫₀^∞ xe^(-x²) dx", opts: ["0", "1/2", "1", "∞"], ans: 1 },
    { q: "What is a differential equation?", opts: ["equation with derivatives", "equation with integrals", "polynomial equation", "trigonometric equation"], ans: 0 },
    { q: "Solve the ODE: dy/dx = y", opts: ["y = x + C", "y = Ce^x", "y = e^(x+C)", "y = x·e^C"], ans: 1 },
  ]
};

module.exports = { questions, LEVELS, LEVEL_NAMES };
